### ISSUE TITLE
Allow user to manually resize grid (presumably via a drag handle)

### ISSUE THREAD

**Issue by mador-tech** [angular-ui/ui-grid#1271]
Is there an option to resize the grid?
If no, are you going to develop this functionality? It is very important to allow users to set the size of some elements in their page.
Thanks

**Comment by PaulL1** [comment]
Perhaps this would tie into #3031

**Comment by mportuga** [comment]
Thank you for this information. I am currently in the process of moving all feature requests and support requests out of the issue tracker in order to keep our bug backlog clear and manageable. You question has been move to the following [link](https://groups.google.com/forum/#!topic/ui-grid-support/d-DmwNzHnV0) and will be addressed by a UI-Grid Dev member when possible.
