### ISSUE TITLE
Cell Validation

### ISSUE THREAD

**Issue by myGitHubForum** [angular-ui/ui-grid#1445]
I am able to do some validation using the ngGridEventEndCellEdit but want to show an error message on invalid input. Is it possible to do it?

**Comment by imbalind** [comment]
See a proposal of validation at #4152

**Comment by parag-patil** [comment]
Hi,

I am using UI grid with validator module. I have below field with validator. I have written custom datatype validator.

{field: 'Qty', displayName: 'Qty', width: '10%', validators: { required: true, datatype: 'int' }, cellTemplate: 'ui-grid/cellTitleValidator'}.

My validator is being called correctly once I edit the cell but in below function, rowEntity is not being updated correctly for rowEntity['$$errors' + colDef.name]. Seems till the time below function is called, validator moudle has not added ($$error) property for rowEntity. My requirement is, if rowEntity do not have property with $$error+.... then save record otherwise do nothing. Is there way to run below function only after validator has updated the rowEntity?

//After cell Edit is completed.
$scope.Grid.onRegisterApi = function (gridApi) {
$scope.gridApi = gridApi;
gridApi.edit.on.afterCellEdit($scope, function (rowEntity, colDef, newValue, oldValue) {
});
};

I hvae opened issue#5577 (https://github.com/angular-ui/ui-grid/issues/5577) but no response yet )
