### ISSUE TITLE
ui-grid font(icon) not working

### ISSUE THREAD

**Issue by yrojha4ever** [angular-ui/ui-grid#1679]
I have font awesome in the website. I have also kept all the file given for ui-grid fonts as well. Still my result is like this:
![image](https://cloud.githubusercontent.com/assets/4167541/4492096/796d9966-4a3e-11e4-8e63-cbc5b550f596.png)

Can anybody help me how to get proper icons. I found this bug in every plunkr provided in the tutorial website too.
Thanks in advance.

**Comment by joepete04** [comment]
In my yeoman based project, after installing angular-ui-grid through bower and implementing my grid, i came across this same problem.  Since the vendor files are minified/concatenated into styles/vendor.css, the grid attempts to find the (undeployed) fonts under styles.

Quick solution for this was to add the following to the Gruntfile.js's copy:dist function:

`, {
          expand : true,
          cwd : 'bower_components/angular-ui-grid',
          src : ['*.eot','*.svg','*.ttf','*.woff'],
          dest : '<%= yeoman.dist %>/styles'
 }`

**Comment by eloytoro** [comment]
The reason this happens is because the font-face url is hardcoded into the css file.
If you minify your css files and place them somewhere else the location for the font face would change as well.
I can't figure out a way to prevent this from happening other than to copy the ui-grid font into your project's /style/ folder
But IMO there should be a way to go around this
Other libraries that use fonts (such as font-awesome or bootstrap-sass) provide sass contants that allow you to change the URL, maybe the UI team could include a provitional sass file that allows this change

**Comment by PaulL1** [comment]
I thought we had an @fonts variable in the .less file?

**Comment by eloytoro** [comment]
There is no .less file in the bower dist

**Comment by fmorriso** [comment]
@eloytoro is correct.
 As of 2016-05-25, I found that after I used Gulp on our project to put things where we wanted, the icons used by CSS classes such as ui-grid-icon-down did not show the proper icon in the grid.

I had to manually copy the *.eot, *.svg, *.ttf and *.woff files to my deployed application's /app/styles/ directory.  Once I did that, the ascending/descending icons started showing up.

**Comment by johnoscott** [comment]
Gulp - I added this explicit copy task:

build.js :
```
/* copy fonts needed by ui-grid to styles/fonts */
gulp.task('copy-ui-grid-fonts', function () {
  return gulp.src(path.join(conf.paths.bower_components, '/angular-ui-grid/fonts/*.{eot,svg,ttf,woff}'))
    .pipe(gulp.dest(path.join(conf.paths.dist, '/styles/fonts/')));
});

gulp.task('build', ['html', 'fonts', 'other', 'copy-partials', 'copy-ui-grid-fonts']);
```

config.js :
```
/* add bower_components path to config */
exports.paths = {
  ...
  bower_components: 'bower_components',
  ...


```

**Comment by dman777** [comment]
This is painful if a fix could be made. Using fountain web generator for angular 1.

**Comment by glolar** [comment]
OK, I am at my wits end with this one. I have the .eot, .svg, .ttf and .woff files in the same folder as my ui-grid.css file, and have verified on Firefox tools' Network tab that these files ARE found when my page loads. However, I STILL get the chinese characters on my grid. I have searched GitHub (and every other forum I can think of) for the past two days, and have tried every proposed solution that is claimed to work, but to no avail. I found one post claiming it was a mimeType issue, but that was for a .NET application. Adding some entries in the .NET web.config file for the mimeTypes fixed their issue, but I am using AngularJS, and I don't have a web.config file. I am not using bower, or anything else like that. Manually downloaded the files and added them to my project's \css folder, along with the ui-grid.css file. Any help to resolve this will be greatly appreciated.
