### ISSUE TITLE
expandable grid subgrid has no access to external scopes

### ISSUE THREAD

**Issue by idot** [angular-ui/ui-grid#1782]
The topmost grid has access to external scope so I can call the delete method on check/uncheck.
The subgrid has no access to the external scope so I cant edit in the subgrid.

http://plnkr.co/edit/EY0RHuHx1oL2ZzHaRjkd?p=info

**Comment by Suku2002** [comment]
Hi, 

I have a requirement to expand the html user control when user clicks "+" expand row header. I have used the expandableRowTemplate and expandableRowScope to display control and to bind the values that I am fetching from server. 

But I am facing an issue, while binding the value to the control. two-way binding not working while expanding the html.

Steps:
1. Created the datagrid and populated with the values
2. "+" expand row header, I have expand the row height and displays the control, not only the row related, it also has some more..for ex: i have grid with user name, id, email id. while expanding I will show, address, phone no...etc. 
3. Fetching value from server related to the userid. But its not binding first time expansion. If I click again it shows the information. 
Tried, 

1. apply(), digest() and timeouts...but grid got expand values are binded to the html control, not displaying the UI.

Please suggest me a solution.

**Comment by jpuri** [comment]
Hi @Suku2002 ,

Please check this: https://github.com/angular-ui/ng-grid/issues/1782#issuecomment-64314687
Let me know if you still have some confusions.

**Comment by Suku2002** [comment]
Thanks for the reply..
I have implemented the gridoptions with expandableRowScope. I can able to bind the value to the html,  but binding happening not based on the current selection. 

Here I am explaining in detail about my problem, 
1. I have panel which holds the UI grid.  And the UI gridOptions has expandableRowScope and expandableRowTemplate.
2. UI grid expandable row element will bind expandable row template [which html].
3. based on the current row selection, i will fetch all the details about that person, so that i could allow them to edit and save to DB.
4. Problem now is, binding happening but it is with previous row information not with the current row.

I am updating the expandable row html template in gridApi.Expandable.on.rowExpandedStateChanged() event. but it not updating first time, when i do expand again it updates. its for all the expandable row expandable event.

two-way binding not updating properly....

suggest me if you have any solution.

Thanks in advance

**Comment by novice3030** [comment]
You might just need to wait for your promise to resolve before setting the
expandable row template
בתאריך 9 במרץ 2015 10:52, ‏"Suku2002" <notifications@github.com> כתב:

**Comment by Suku2002** [comment]
I have tried that..but the expansion is happen before timeout/inverval. but its not working.

**Comment by jpuri** [comment]
@Suku2002 , if possible can you please share a plunkr for this issue.

**Comment by LazyCod** [comment]
Hi jpuri,
ng-click is working for the outer grid with ```grid.appScope.clickMe()``` scope. But it is not working in subGrid. In subGrid i am invoking the method as ```grid.options.expandableRowScope.clickMeSub()``` and ```grid.expandableRowScope.clickMeSub()``` . 

```expandableRowScope: {
      clickMeSub: function(){alert('hi');}
    }```
Plz check the plnkr below
http://plnkr.co/edit/nJLcMLBwdgPzOQUvgjQT?p=preview

**Comment by manishsoni07** [comment]
Hi Jpuri,

can i expand ng-grid on 3 level. if it is possible so please help.

Thanks
Manish

**Comment by Natasha023** [comment]
Resolve this issue by set the minRowsToShow and scroll bar will show up if rows > minRowsToShow
