### ISSUE TITLE
Conditionally show horizontal scrollbar based on whether or not the columns fit completely in grid space

### ISSUE THREAD

**Issue by archerchiu** [angular-ui/ui-grid#1854]
Has any setting to work it? Because horizontal scroll bar is always not shown in some using situation. By the way, why the horizontal scroll bar appears in the <a href="http://ui-grid.info/docs/#/tutorial/310_column_moving">310_tutorial</a>? It is the same output after appending the  'ui-grid-auto-resize' directive. Indeed, if i dragged the scroll bar, it will shrink like this.
![2014-10-17 03-07-07](https://cloud.githubusercontent.com/assets/2604264/4675511/88911aa8-560f-11e4-82b7-5a953e68db52.png)

**Comment by AgDude** [comment]
Here is a plunker where I have partially implemented this: http://plnkr.co/edit/20AOnC

The method there works for the initial columns, but if columns are added/resized, there isn't a good way of recalculating. Per a discussion on gitter, perhaps a new core event of ```onStylesRegistered``` would be nice, since then we could get the calculated column widths.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
