### ISSUE TITLE
Need a sort icon for ".ui-grid-icon-blank::before" class as it is empty now

### ISSUE THREAD

**Issue by iamfelix8** [angular-ui/ui-grid#2274]
This Sort icon should be of similar to wikipedia tabular data sort icon
Example: http://en.wikipedia.org/wiki/List_of_text_editors

**Comment by aranta-rokade** [comment]
Even I am facing the same issue. Currently, when a column is not sorted, it does not show an icon. But I require an icon to be displayed indicating that the column can be sorted. Such as this -  [http://fontawesome.io/icon/sort/](url)

The css has a class - 
`.ui-grid-icon-blank::before {
  width: 1em;
  content: '\c358';
}`
but on changing the `content` of the icon, the icon does not appear due to another class `ui-grid-invisible` applied on it. On removal of that class the priories are visible as well, which is not required.

**Comment by addRow** [comment]
Arnata, did you find any solution on this?
