### ISSUE TITLE
Expandable Grid height not working correctly

### ISSUE THREAD

**Issue by kevin-sage** [angular-ui/ui-grid#2300]
If there is no style on the div for the template of the expandable grid template, the div is given a style="height: 330px;".  I am trying to control the height of the grid using a variable on the row.entity (i.e. using rowExpandedStateChanged to load the data for the subgrid), and I have everything wired up and it would be working, except something is adding the height to the style.

I am trying to figure out what is setting this, and if this is something that we can either remove or make configurable?

**Comment by PaulL1** [comment]
@jpuri: I think @kevin-sage is saying that we have a setting for expandableRowHeight, but it's not getting applied to the template.  Is that something we could do?

**Comment by jpuri** [comment]
Hey @PaulL1 , I guess what @kevin-sage wants to say is that though 'expandableRowHeight' is getting applied to expanded row, is there a way we can make height of expanded row template same as expanded row that is 'expandableRowHeight'.

@kevin-sage a possible way of doing that could be adding the value of height to expandableRowScope. The value will then be available to you in expanded row template which you can use with ng-style to change height of the expanded template.

**Comment by jpwits** [comment]
@kevin-sage : I think we will have to look at fixing the scrolling so the expandableRowHeight is defined on the sub grid row, I rarely use a sub-grid with fixed row numbers, since it's a foundation change it would probably be best to do it soonest, but this is 'hot' functionality used in almost all cases....would check if I can contribute...but way to busy right now...

**Comment by qikevinjkw** [comment]
@jpuri Can a sub-grid be expanded completely(no scrolling within sub-grid)? For example, if each row has a sub-grid, and each sub-grid differs in height, can I have the sub-grids expand fully when I expand them? I can't set the expandableRowHeight since that would give a fixed height for each sub-grid, but each sub-grid differs in how many rows it has, thus their height differs too. <br><br> Also, regarding your previous comment 

> Currently we have a limitation of having fixed height of subgrids, this is because of the way scrolling is 
implemented in grid. 

I'm curious as to why treeView grid can have child rows of different heights(http://ui-grid.info/docs/#/tutorial/215_treeView) but sub-grids can't.

**Comment by deepjain1290** [comment]
any update

**Comment by jpwits** [comment]
Hi,

dit figure this one out, had to use a diffferent property, but I'm not
using UI-grid anymore, the setup, etc was just not flexible , and it tied
me down to much

Jos

Kind Regards,

Jos Wilson
0792180819
jpwits@gmail.com

**Comment by sujayjakhadi** [comment]
Any update on dynamic heights based on number of rows?

**Comment by jyotsnam** [comment]
I am also looking for dynamically adjusting height of 3 layer sub-grid. Any update on this?

**Comment by nsksaisaravana** [comment]
Any update on this, most important feature.

**Comment by mportuga** [comment]
Any help would be appreciated

**Comment by chintu538** [comment]
problem with expand collapse button- Using dynamic row height in angular UI-grid, each row takes height according to its content, but expand/collapse column is not aligned with corresponding row. My requirement is to get it aligned with its corresponding row. If that requirement is done the Grid will be intact with browser, when ever browser is resized. Any suggestion on how to get this to work? Thanks.

these are the styles i have used .ui-grid-cell-contents for content under each cell

```
.ui-grid-row, .ui-grid-cell 
  {
    height: auto !important;
  }

.ui-grid-row div[role=row] 
 {
    display: flex ;
    align-content: stretch;
 }

.ui-grid-viewport 
 {
    word-wrap: break-word;
    white-space: normal !important;
 }

.ui-grid-cell-contents 
 {
    padding:5px;
    box-sizing: border-box;
    font-size: 14px;
    display: flex;
    align-items: center;
    white-space:normal !important;
    word-wrap: break-word !important;
 }
```
rowHeight is specified 'auto' in GridOptions

$scope.productGridOptions = {
data : 'Details',
rowHeight: 'auto',
columnDefs : [
{
},
.
.
.
]

};
![posting](https://user-images.githubusercontent.com/45032523/48476993-768aa880-e826-11e8-9054-59ff0b48de68.PNG)
