### ISSUE TITLE
Add support for top pager

### ISSUE THREAD

**Issue by benjamin0101** [angular-ui/ui-grid#2473]
Moving to angular from jquery and replacing jqgrid which had support for top pager.

Basically it is a configuration option that allows the pager to be displayed at the top of the grid also.

Could someone point me in the right direction on how to do this? With some direction I'm interested in contributing this feature.

# Proposal

### Properties

- topPager - enables top pager (defaults to false to preserve backwards compatibility)

**Comment by PaulL1** [comment]
I think @brianchance has done most of the work on paging, he would probably have an opinion and guidance on how to go about it.

**Comment by brianchance** [comment]
Playing around with it, if you prepend instead of append in the uiGridPaging directive, then remove the absolute positioning and top/bottom, and it works. 

When at the top, the .ui-grid-pager-panel needs a clearfix so it has height, not sure how that should be handled without creating dependencies. 

Looks like it will need a border bottom since the header relies on the outer border for framing.

**Comment by benjamin0101** [comment]
@brianchance thanks for some guidance. can you elaborate more on your dependencies comment?

**Comment by brianchance** [comment]
The pager panel needs a clearfix, I use bootstrap which has the class defined. Relying on bootstrap would be a dependency.

**Comment by jeuvin** [comment]
This feature is not working, what was the resolution for this?
