### ISSUE TITLE
Pagination styling is broken on IE9.

### ISSUE THREAD

**Issue by alexandery** [angular-ui/ui-grid#2552]
Pagination styling is broken on IE9. Here are the screenshots from IE9 and FF of one of the tutorial pages:

IE9:
![pagination ie9](https://cloud.githubusercontent.com/assets/3676316/5748021/caf4c6e4-9bf9-11e4-9696-7074c1813bf5.png)

FF:
![pagination ff](https://cloud.githubusercontent.com/assets/3676316/5748028/d636cb6a-9bf9-11e4-9e3f-a9e083696d3a.png)

**Comment by EricS91** [comment]
One solution I've found is:


    .ui-grid-pager-panel {
        position:relative;
        display: inline-block;
    }

    .ui-grid-pager-max-pages-number {
        vertical-align: top;
    }

the ui-grid-pager-max-pages-number vertical position might not be the best but because of the line-height of the footer it's difficult to position it properly. If the line height is set to 1 then vertical-align: middle would work fine. 

Hope this helps

**Comment by PaulL1** [comment]
Is this still happening?  I saw a different IE pagination issue that seemed to suggest it was slightly overlaying the scrollbar, which implies this isn't happening any more.

**Comment by zhusulai** [comment]
Can confirm this issue is still happening on IE9. 

![image](https://cloud.githubusercontent.com/assets/11685777/7004891/e9e71594-dc3f-11e4-9368-c349d88f7824.png)

**Comment by hikalkan** [comment]
Hi,

Not only IE9 but also for IE11. You can check http://ui-grid.info/docs/#/tutorial/214_pagination
![clipboard01](https://cloud.githubusercontent.com/assets/1210527/8895020/c925508c-33d3-11e5-91a5-cfc120fb8850.png)

**Comment by JLLeitschuh** [comment]
This is an issue that is not exclusive to IE. Seems very inconsistent and hard to reproduce.

**Comment by hikalkan** [comment]
Interesting.. but it always happens when I try :)

**Comment by dalin92** [comment]
Anyone know anything more about a fix for paginationg overlapping the grid? I need to support IE and I'm unsure how to fix this.

**Comment by ashwin027** [comment]
@JLLeitschuh The reason why this is happening is because the adjustment values are different in IE when compared to chrome and firefox. The adjustment is subtracted from the total height to get a final viewport height.

e.ownerDocument.defaultView.getComputedStyle(e, null)

The above statement is used in the getStyles function which returns a different height in IE when compared to other browsers. The reason being that the height in IE is excluding padding whereas the height in chrome and firefox is including padding. 

Possible fixes:

Option 1: We could change the box-sizing property to content-box and let the code handle it,

File: Pagination.less
```
.ui-grid-pager-panel {
    position: absolute;
    left: 0;
    bottom: 0;
    width: 100%;
    padding-top: 3px;
    padding-bottom: 3px;
    box-sizing: content-box;
}
```

File: pagination.js
```javascript
uiGridCtrl.grid.renderContainers.body.registerViewportAdjuster(function (adjustment) {
   adjustment.height = adjustment.height - gridUtil.elementHeight($elm, "padding");
   return adjustment;
});
```

Once we change to content-box, the padding will be ignored when the height is computed which brings all browsers on the same playing field. Once we pass option "padding" to the elementHeight function, it reduces the height by the padding (6px) which aligns the controls correctly (IE10+).

PR #4616

Option 2: 
We can add a min-height property of 32px to the .ui-grid-pager-panel class and then add another function to the gridutils to pull the min-height property for the panel and reduce the height of the viewport by the min-height which should fix this issue. I dont have a PR for this but let me know if you need one. This option is more invasive than option 1.

**Comment by SoundLogic** [comment]
+1 for this issue - happens consistently for me

**Comment by anitapillai** [comment]
+1 for this issue - happens consistently

**Comment by TeChn4K** [comment]
Same problem. Chrome is OK but Firefox not

**Comment by TeChn4K** [comment]
I use another temp fix. My needs : hidden scrollbars, adaptive height and pagination.

ui-grid js conf :
```
...
enableHorizontalScrollbar: 0,
enableVerticalScrollbar: 0,
...
```
css overload
```
.ui-grid, .ui-grid-viewport {
  height: auto !important;
}

.ui-grid-pager-panel {
   position: relative;
   left: auto;
   bottom: auto;
   padding-top: 0;
   padding-bottom: 0;
}

.ui-grid-pager-container, .ui-grid-pager-count-container {
 margin-top: 10px;
}
```

**Comment by jodibean** [comment]
I have issues with IE11 and FireFox (FireFox looks way worse). Is there a workaround?

**Comment by marcindopart** [comment]
Only for IE you can:
`.ui-grid {
    position: relative;
}`
and
`.ui-grid-pager-panel {
     position: absolute;
     left: 0;
     bottom: -3px;
     width: 100%;
     padding-top: 3px;
     padding-bottom: 3px;
     box-sizing: content-box;
}`

For me this solution looks good (screens below)
![screen](https://cloud.githubusercontent.com/assets/6822976/14671204/ec9920ca-06f0-11e6-9c9c-34e3424d76fa.png)
(IE11)
![screen2](https://cloud.githubusercontent.com/assets/6822976/14671245/1a58b926-06f1-11e6-8fb8-72a1aa24c0dd.png)
(IE9)

**Comment by dipankarpaul** [comment]
The above solution worked for me. You can also follow the below link.

[http://dp1981.blogspot.com/2016/07/ui-grid-ie9-pagination-issue.html]

**Comment by vcfvct** [comment]
Having the same issue in IE9 which the `position:absolute` + `bottom:-30px` does not work. 
Have to apply the below css: 

```
.ui-grid .ui-grid-pager-panel{
  bottom: -5px;
  position: relative;
}
```

**Comment by mportuga** [comment]
Removed IE9 support.

**Comment by JLLeitschuh** [comment]
@mportuga When you make a release with that change. Remember that according to Semver, that's a major version breaking change and you should rev the major version number.

**Comment by mportuga** [comment]
@JLLeitschuh So, the reason for not making it a major version at the moment is because 5.0.0 is currently planned to be the angular 5 release. So I will unfortunately not be following Semver conventions correctly for the near future.

**Comment by JLLeitschuh** [comment]
Fair enough.
