### ISSUE TITLE
expanding some rows then scroll down. empty gap appears at the bottom

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ui-grid#2759]
http://ui-grid.info/docs/#/tutorial/216_expandable_grid

try expanding some rows then scroll down. empty gap appears at the bottom

![image](https://cloud.githubusercontent.com/assets/3965957/6168684/14529734-b2d0-11e4-8c40-aee4c2d7df46.png)

**Comment by PaulL1** [comment]
@jpuri, do you have any thoughts on this one - is it an issue you've seen before?

**Comment by jpuri** [comment]
Hey @PaulL1 ,
This is a known issue with our scrolling. In case there are expandable rows it does comes.

**Comment by mikila85** [comment]
its not only at the end even just expending few, then try scrolling down LIL bit... the whole table becomes empty :(

cant use this.

**Comment by ddelapaz** [comment]
I am not able to replicate this issue, is it still present? I'm using v3.0.0-RC.18-d9b2314

**Comment by jacekradko** [comment]
@ddelapaz This is still an issue in 3.0.0-rc.20

**Comment by jpdesigndev** [comment]
I'm seeing the same issue here. In my case it has nothing to do with expandable rows as I'm not using that feature.

**Comment by c0bra** [comment]
The problem occurs with displaying a static number of extra rows on the bottom and top, based on `excessRows`, when the rows are variable height.

By default 4 rows covers rendering above/below the grid in a way that prevents gapping, normally
But when the first unrendered row is 150px tall instead of 30px, suddenly there's a big unrendered gap because you're expecting the space to be ABOVE the top of the grid.

We should be able to detect this by looking at the margin offset and the scrolltop. If the margin extends BEYOND the scrolltop (i.e. is larger) then we're not displaying enough rows. So in adjustRows we detect this condition and simply add extra rows until on whichever side until they display enough to extend from the top of the first rendered row to the bottom/top of the viewport.

**Comment by c0bra** [comment]
Adding a check to walk back through unrendered rows till we've rendered enough to cover the viewport is close, however we run into a problem here:

```javascript
self.prevRowScrollIndex + self.grid.options.scrollThreshold
```

If we haven't hit the scroll threshold we won't updated the rendered row range.  I'd rather not have to recalculate all the row heights on every scroll to see if we need to alter the rendered range, but it may be unavoidable...

This is only a problem scrolling upwards, as well.

**Comment by tiddle** [comment]
Just wondering what the status of this was? As this bug is happening to me without expanding rows.

**Comment by c0bra** [comment]
@tiddle It's a pretty rough issue to solve. I've spent some time tackling it but need a solid chunk that I can devote to getting a solution.

**Comment by tiddle** [comment]
@c0bra, I completely understand, is there some way of manually avoiding the issue? Or a workaround?

**Comment by c0bra** [comment]
Moving this to 3,1. We'll mark the expandable feature as "beta" for the 3.0 release so that it's not blocking us.

**Comment by lvarayut** [comment]
I'm having the same issue using 3.0.7.

**Comment by AbhiPanda** [comment]
We are having pre production issue for this issue and seems like a blocker to us. Any updates on this fix? or any workarounds ?

**Comment by mikila85** [comment]
Ye bro, use a different lib.. I ended up using telerik kendo grid. Amazing and bug free.

**Comment by johnib** [comment]
Is this bug planned to be solved in version 3.1? 
Thanks.

**Comment by aitorMolinuevo** [comment]
@PaulL1 Is this bug resolved?

**Comment by nithuKrish** [comment]
Is this bug resolved
