### ISSUE TITLE
Issue with ui-grid-pagination and ui-grid-auto-resize with 100% height

### ISSUE THREAD

**Issue by willi1s** [angular-ui/ui-grid#2818]
When using ui-grid-auto-resize in a div with a height of 100%, if ui-grid-pagination is enabled, the pagination information ends up off the top of the page?
Example of the issue is here: http://plnkr.co/edit/jOwMncNxQ6reuX1U70UV

**Comment by shamoh19** [comment]
Any update on this issue?

**Comment by mportuga** [comment]
I had to recreate the plunker to get this to work and what I found was that setting the container height to 100vh, instead of 100% worked great. If you set it to 100% in the latest version, it seems that the grid just keeps resizing itself until all rows are visible:
http://plnkr.co/edit/zX3XEvSYgd9gfGX9
