### ISSUE TITLE
ng-grid does not work when using 'sortFn' and 'groups'

### ISSUE THREAD

**Issue by felipeburegio** [angular-ui/ui-grid#2846]
Hello,

I wonder if it is possible to customize the sorting and grouping to use the same column.
I made an example in Plunker where the 'groups' option is commented out. When this line is uncommented the grid does not display any records.

Link Plunker: http://plnkr.co/edit/krlAsVr7NM30fFljyaQH

Thank U.

**Comment by jjkovacs** [comment]
It **is** possible to provide a sortFn for a grouped column.

I think what's causing your issue is a mixture of how you're using the `field` property, and the structure of your data. 

The `field` property is meant, first and foremost, to be an identifier for the columns, and secondly to provide a shortcut for displaying properties on your grid entity in a column. The `groups` array needs to contain the `field`s to group on.

Both of your columnDefs have the same value for the `field` property. Also, the `groups` array contains a string that doesn't correspond to a `field` on either of your columnDefs.

Fixing this will get grouping working for the name column, as well as standard sorting on both columns (with or without sortFn). However, since the sorting you're trying to do is a bit atypical (sorting one column entirely on another column), you might want to make use of `useExternalSorting` instead of `sortFn`. This will allow your gridOptions to be cleaner, as your `field`s in the columnDefs can correspond to the entity properties, and you won't need to override any templates.

**Comment by imbalind** [comment]
I'm closing this since we're not supporting 2.x anymore. Anyone wiiling to take on from here, feel free to fork.
