### ISSUE TITLE
Need the ability to provide the title header bar for the grid

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ui-grid#2876]
It would be nice to have ng grid supported with the feature to support table name too. So that we no need to go for external html  just  to name  the grid. We should be able to provide name for the grid through grid options settings.  It would be awesome, if we have some option  for header bar where we can specify title, back ground color, boarder with in ng grid directive. please consider the quest if it is feasible.

**Comment by c0bra** [comment]
You can do what you're describing with a custom header template and CSS. We are trying to keep from adding all sorts of extra options into the grid because many people won't use them. If it's something that's achievable with a couple tweaks by the consumer then there probably isn't a compelling reason to write it into the grid.

You could always write a plugin that does this, though.

**Comment by madasuk** [comment]
Yes c0bra, right now I am doing like that only, but it makes the grid  full featured without going for any external coding. If it is a simple change you can try to consider this request to make the grid full featured otherwise you can close the issue.

**Comment by c0bra** [comment]
I'll mark this as an enhancement.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
