### ISSUE TITLE
If column name has a decimal number, data for column do not render

### ISSUE THREAD

**Issue by joncortez** [angular-ui/ui-grid#2911]
If a column name has a decimal number (see example below), the data for that column DOES NOT render.

``` javascript
$scope.myData = [
    {
        "firstName": "Cox",
        "lastName": "Carney",
        "some 2.5 column": "foo"
    }
];
```

Here is the plunk - http://plnkr.co/edit/MoZvrOlSbyDJ5CrgugZu?p=preview

**Comment by PaulL1** [comment]
I had a play around with your plunker, and extended it: http://plnkr.co/edit/fP2sRktbf3Oif9v44Rcm?p=preview.  I think it is a defect/limitation, but I suspect this is a low priority fix - the obvious answer would be to reprocess the data to change the name of the column.  I suspect that the problem is that we allow column fields to have dot syntax - so you can have a field that is `address.street`.  That means we're treating the dot as meaning a sub-entity, and we don't know that you mean it to be the actual column name.

Here is an example plunker that renames the data:

**Comment by c0bra** [comment]
@PaulL1 I think we'd need to either depend on this library or borrow from it to be more robust about object path processing: https://github.com/mariocasciaro/object-path

**Comment by JLLeitschuh** [comment]
Doesn't angular have a built in way of doing this?

**Comment by kolekaramol** [comment]
This has been reproduce for me with same scenario
