### ISSUE TITLE
Set all cells in a row editable

### ISSUE THREAD

**Issue by genu** [angular-ui/ui-grid#3122]
Is there a way to set all the cells in a particular row as editable?

**Comment by PaulL1** [comment]
If you mean to show the edit widgets on all the cells, then no, at present there is not.  It's been asked for a few times though, so I'll leave this open as a request.

**Comment by genu** [comment]
Can you give some insight on how this could be done?

I can work on a pull.

**Comment by PaulL1** [comment]
OK, probably two things.  

Firstly, I think @swalters has just rewritten a bunch of this, and I think there's a PR with his branch that handles focus and stuff, probably check what I tell you against that because it may have changed.

Look at the first timer guide: https://github.com/angular-ui/ng-grid/blob/master/FIRST_TIMER.md and contributing.md and developer.md, if you haven't already.

Look in the edit feature - everything you do needs to be localised to there.  https://github.com/angular-ui/ng-grid/tree/master/src/features/edit

At present when a cell gets focus it triggers an event on the grid-cell (there is a directive in the edit feature that stacks on top of the standard grid-cell).  It replaces the contents of the cell with the editor.

I'd be heading for an approach where you notice the focus on the cell, and broadcast a "receive row focus" event, including the row that you're on.  All the other cells would listen for that event, and also go into edit mode if the row matches their row.  Not sure that actually works, but it sounds plausible.

Tricks and traps - when you get an event, you need to check it's also for your grid - some people have multiple grids on a page, and maybe some of them share data so they think they have the same row.  And check what @swalters did, because I'm pretty sure he changed how a cell knows it has focus - I think we've shifted to a virtual focus rather than native grid focus.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by msrikanth508** [comment]
@PaulL1 / @c0bra / @jpuri  I have the same requirement here. I need to set entire row in edit mode instead of individual cell editing. I have created a POC by modifying source file.
Preview: http://embed.plnkr.co/VO6F3vlOOwaudfi3RSVA/ 
Try to edit a cell/press edit button.

Output would be:
![image](https://cloud.githubusercontent.com/assets/8520311/12348413/2e4e27f4-bb8d-11e5-9798-a2daff08e1ea.png)

We could do inline editing for nested grids as well since it will be a separate grid entity like 
![image](https://cloud.githubusercontent.com/assets/8520311/12348421/4c2f2e1c-bb8d-11e5-9eff-16d2faa41d70.png)

Use case:
User has to edit entire row and single row at a time. Before enabling row edit we need to check all rows whether they are in edit mode or not, if yes perform CANCEL_EDIT_CELL

Implementation Part:
We don't have properties for cell to listen edit event, So I have added couple of properties for cell. I am using watch to listen this property and act accordingly.

Please go through the code and let me know whether i'm doing in right way!

**Comment by dishant8** [comment]
@msrikanth508 looks quite promising. I have a similar use case. Also after editing, is controller being notified with the updated data? and are their any plans to implement this as a permanent feature in grid?

**Comment by komalgithub** [comment]
msrikanth508 your UI editable grid is no longer on the rawgit , can you please provide the updated URL, its urgent.

**Comment by devanshuGit** [comment]
@msrikanth508 : Your version of inline editing doesn't work with grouping. It starts breaknig because grouping inserts a header row and it couldn't find 'IsEdit' property on the header row. I tried to look but doesn't have much idea how to solve it. Can you give some pointers or is it already handled in other version you are using in your project. Please reply, i am in need of the solution for inline edit.

**Comment by lbogdan4** [comment]
@msrikanth508 Your demo is awesome but is there a working demo using ui-grid 4 ?

Thank you

**Comment by mistvan** [comment]
Same question from my site @lbogdan4 :)
