### ISSUE TITLE
Support for Angular Material Design

### ISSUE THREAD

**Issue by frodefi** [angular-ui/ui-grid#3210]
Support for Angular Material Design so that ui-grid follows the material design principles. Would that be possible to include?

**Comment by c0bra** [comment]
I saw your SO post. Can you're clarify exactly what you're wanting? For a grid that uses Angular Material widgets and kinda looks the same?

Strictly following all the the principles, especially involved stuff like animation with ui grid is probably going to be a bit tough since it wasn't built with that in mind, but all the templates and CSS can be adjusted.

Take a link at the customizer link on the front page to set how you can tweak things.

**Comment by frodefi** [comment]
> For a grid that uses Angular Material widgets and kinda looks the same?

Yes to this, no to strictly :)

Ok, will check out tweaking possibilities, thanks. Would be nice with some "out-of-the-box support" sometime in the future.

**Comment by c0bra** [comment]
Unfortunately the Angular UI-Grid team is MUCH smaller than both the Angular team AND the Angular-UI team, so getting stuff like this done relies a lot on community involvement and available time.

Any help in making something like this a reality would be very welcome!

**Comment by DmitryEfimenko** [comment]
+1

**Comment by frodefi** [comment]
Check out [Angular Data Table](http://swimlane.github.io/angular-data-table/), a datatable made by some smart people and they have used Material Design (but you can customize as you like). Highly recommended and probably better than ui-grid. Check out their github-page too. Angular Material guys are also [looking at it](https://github.com/angular/material/issues/796) for their table version.

**Comment by rplute** [comment]
+1

**Comment by Bouhnosaure** [comment]
+1

**Comment by RimvydasUrbonas** [comment]
+1

**Comment by jodibean** [comment]
+1

**Comment by bastienJS** [comment]
+2

**Comment by cb109** [comment]
+1

**Comment by dan2k3k4** [comment]
+1

**Comment by michelem09** [comment]
+1

**Comment by tuckerjt07** [comment]
@c0bra @PaulL1 I have created an initial working ui-grid using angular-material-design to provide the material design elements. So far I have completed the column headers, column menu buttons and menus, grid menu button and menus, textbox column filters, and checkboxes for selection. I only made slight changes to three or four js files, had to load the templates via $compile to work with the ngMaterial directives, changed the html templates to use ngMaterial elements, and extended the .less files. The elements still use all of the original ui-grid classes, either using slight tweaks to the original class or a md-grid class to extend the element. What would you like to do with this? I used your code to create it so if you would like to bring it into the project that makes sense. If not, please let me know so that I can host it for the community. UI-Grid is an amazing, widely used tool so having a Material Design flavor is needed.

**Comment by swalters** [comment]
@tuckerjt07 good job!  I agree that it would be a great contribution to the project.  Do you have a public repository so I can review the changes?  Ideally, this would be a feature that someone could add to their project by adding the module and directive to ui-grid.

**Comment by DmitryEfimenko** [comment]
way to go @TimDumol! You are my hero! Can't wait to see this as a feature in ui-grid!

**Comment by tuckerjt07** [comment]
@swalters I do but it isn't in the format that would support that currently. This is the repo, https://github.com/tuckerjt07/ui-grid. My thought was make the slight tweaks to the necessary directives, not changing functionality but to move the templateUrl into the link function using compile to the ui-grid base then allow the user to select the standard ui-grid templates or the md-grid templates based upon preference. One other feature I am working on is to move the grid-menu to a toolbar instead.

**Comment by jmls** [comment]
is there any progress on this ? I really would love to use a material theme

**Comment by abartolo** [comment]
+1 any update?

**Comment by murlex** [comment]
+1 any news?

**Comment by icenold** [comment]
any news?

**Comment by maxhan247** [comment]
+1

**Comment by mesilov** [comment]
+1

**Comment by rubavathy** [comment]
+1

**Comment by tuckerjt07** [comment]
I still have the code to implement the material grid but I'm not sure how the owners of the repo would like to go about including it.

Most of it is just template and css changes but there were a couple of the js functions I had to modify as well due to needing multiple isolated scopes.

**Comment by Ruud-cb** [comment]
@frodefi I actually just thinking about switching to ui-grid. Indeed that one looks better and has better user experience, yet I believe ui-grid has far more out of the box customization. In angular-data-table you would need to edit all the different templates. Still deciding though.
@tuckerjt07 Will your code have the same column drag and drop effect like the one mentioned by frodefi? [click on sorting](http://swimlane.github.io/angular-data-table/ ).

**Comment by tuckerjt07** [comment]
@Ruud-cb It has drag and drop but it doesn't swap the headers as ghost text like the example.
I'm really at loss as to what to do with the code though. I don't want to put it in a forked repo because I still use the ui-grid internal functions and that would create an upgrade path nightmare on my end.

**Comment by tit1** [comment]
@tuckerjt07 This is me being greedy, but i would say fork it. That way your modifications are not only there for people like me that are moving from bootstrap to material, and want to use ui-grid, but ui-grid team. After looking over your code there may be a way for them to implement your changes back in the core package.

**Comment by Frankwalraven** [comment]
are there some developments on the @tuckerjt07 material theme

**Comment by Ruud-cb** [comment]
Almost two months later I finally went for Ag-grid, not advertising here, but it does ghost swap, probably just some styling todo if you would like to get the same material design effect.

**Comment by samsfisher** [comment]
@tuckerjt07  any developments

**Comment by patoncrispy** [comment]
I am expressing interest in this also. :)

**Comment by mcblum** [comment]
This would be the absolute best. We just found this repo and it is leaps and bounds above what we were using but we need to bring it up to modern design standards. If anyone is a designer (I am not) and has something, we would love to use it!

**Comment by hksfho** [comment]
+1
