### ISSUE TITLE
setThisRowInvisible isn't working

### ISSUE THREAD

**Issue by YonatanKra** [angular-ui/ui-grid#3212]
Hi,
I've created a small demo: http://plnkr.co/edit/m6f5282YS5eEBP3VHgjl
The button below the grid is supposed to toggle all of the rows invisible and visible.
Is this a bug or am I using this incorrectly?

**Comment by PaulL1** [comment]
This is a bug, you're also using it a little incorrectly.

The bug is at line 52 of `gridClassFactory`, in the `allRowsVisible` rowsProcessor.  It reads:
`              row.visible = true;`
but should use `evaluateRowVisibilitity` like this:
`              row.visible = row.evaluateRowVisibility( true );`

I can fix that.

In your code, you seem to be using row.setThisRowInvisible, and then row.clearRowInvisible.  For consistency both should without the `this`.  But actually you should be using the api:
`gridApi.core.setRowInvisible` and `gridApi.core.clearRowInvisible`.

**Comment by PaulL1** [comment]
Actually, looking at what I've done in this area, I've overcomplicated it and I think it'll be slow (not to mention error prone).  Only the user should really set a visibility override, everything else should be re-evaluated on every execution of the rowsProcessors.  I think I need to rewrite the various rows processor so that each sets any row it wants to change to invisible, and then drops that row out of the list it passes to the next processor.  Then, for example, we wouldn't sort rows that filtering has already determined we shouldn't see (but we would sort rows before grouping them, as grouping runs after sorting).

**Comment by yccteam** [comment]
Thanks.
So, ```setThisRowInvisible``` is a private method I should not use.
I thought a row should have its own function for changing visible state. But invisible(row) works fine. 
Regarding your efficiency comments - sounds like a great boost. Looking forward to the change.
Thanks again :)

**Comment by yccteam** [comment]
I've tried to use ```gridApi.core.setRowInvisible``` with no success. I've also tried your suggested fix (```row.visible = row.evaluateRowVisibility( true );```) but this made data to be invisible no matter what I did.

**Comment by PaulL1** [comment]
OK, I've pushed this update today in #3244.  

This gives a noticeable performance improvement on the large data set tutorial: http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance

If you sort by gender you'll see it's reasonably slow, if you then filter by age (say, '54'), then the sort becomes a lot faster.  I've dropped the invisible rows out of the rows that are propagated by the rowsProcessor, I haven't seen any reason that the invisible rows need to be processed.

**Comment by yccteam** [comment]
Works!
http://plnkr.co/edit/m6f5282YS5eEBP3VHgjl?p=preview

**Comment by aih** [comment]
grid.core.setRowInvisible is again not working in v3.2.9, though it is working in v3.2.1. Is this a known bug in v3.2.9?

**Comment by mportuga** [comment]
@aih Thank you for doing the research. I will take a look.
