### ISSUE TITLE
odd / even with virtualization

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ui-grid#3369]
At the moment UI-Grid is implementing odd / even row colors in the css with the following rule :
.ui-grid-row:nth-child(even) .ui-grid-cell {
  background-color: #f3f3f3;
}

The issue though is that with the row virtualization, if a single row is hidden, all the divs will flip color.
Maybe we could have something like rowClass (as opposed to cellClass) to apply a rule on every odd row ?

**Comment by c0bra** [comment]
Is this not the expected behavior? Is it the DATA that's styled or the GRID ROW CONTAINERS that are styled? If it's the just the data shifting over a constant background then if I hid a row I'd expect the lower rows to shift up and fill in the missing row, which would look like the colors "changing".

**Comment by cookednoodles** [comment]
The main issue is that the odd / even is being done in CSS and not in the code.

In our example we have 5 very high rows visible on screen. When scrolling down the page UI-Grid will hide the unseen divs and then remove them, meaning that a div that was an an 'even' row can become 'odd'; meaning that the css doing the odd/even zebra'ing will cause all the lines to switch color.

**Comment by PaulL1** [comment]
@cookednoodles: I think you're saying that just scrolling can toggle the colouring, not hiding rows?  Is that correct?

I agree with @c0bra that hiding a row should change the colour of the rows below.  I'm ambivalent on whether scrolling should change the colours - they're really just a visual break between rows rather than meaning something, conversely if you're trying to keep track of a particular row whilst scrolling it would be hard if it changes colour - you'll lose it.

**Comment by kaelhem** [comment]
With the RC21, I'm experiencing a similar issue.
I'm able to fix it with a custom row template in the grid options, like this : 

```javascript
rowTemplate: '<div ng-class="grid.appScope.rowColor(row)">' +
            '<div ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }"  ui-grid-cell></div>' +
        '</div>',
```

and, in the scope : 

```javascript
$scope.rowColor = function(row) {
    var idx = $scope.datas.indexOf(row.entity);
    return idx % 2 === 0 ? 'is-even' : 'is-odd';
};
```

after that you can apply css to make the background color switching correctly during scroll : 

```css
.ui-grid-row .is-odd .ui-grid-cell { background-color: #fff; }
.ui-grid-row .is-even .ui-grid-cell { background-color: #ccc; }
```

of course this will not work if you hide rows programatically...
I hope that will be helpful !

**Comment by lbntly** [comment]
I'm affected by this issue as well. Unfortunately, while @kaelhem's solution solves this problem, it degrades performance quite a bit. Since my grid has a lot of other bindings it's not going to be sufficient. If anyone has found another workaround for this, I'd love to know what you did! Thanks.
