### ISSUE TITLE
Range filter with select

### ISSUE THREAD

**Issue by cyberlake** [angular-ui/ui-grid#3381]
I have column with integer values and I'm trying to set filter with select which contains some ranges. For example my data can be any number between 0-1000 and I'm want to have ranges like 0-10, 11-50, 51-200 etc.

I tried the code below, but it isn't working.

``` javascript
{name: 'Company Size', enableHiding: false, field: 'company_size', width: '10%',  filter: {
          type: uiGridConstants.filter.SELECT,
          selectOptions: [
            { value: '0-10', label: '0-10' },
            { value: '11-50', label: '11-50' },
            { value: '51-200', label: '51-200' },
            { value: '201-500', label: '201-500' },
            { value: '501-1000', label: '501-1000' }]},
          cellFilter: 'mapCompSize'}
```

and I have filter which is:

``` javascript
.filter('mapCompSize', function() {
    var getAges = function (min, max) {
      var ages = [];
      for(var i=min; i<=max; i++)
      {
        ages.push(i);
      }
      return ages;
    };

    var sizeHash = {
      '0-10': getAges(0, 10),
      '11-50': getAges(11, 50),
      '51-200': getAges(51, 200),
      '201-500': getAges(201, 500),
      '501-1000': getAges(501, 1000)
    };

    return function(input) {
      if (!input){
        return '';
      } else {
        return sizeHash[input];
      }
    };
  })
```

Is there any better solution?

**Comment by PaulL1** [comment]
Filtering doesn't work against the filtered (in the angularJS filter sense) data.  So if you're using a cellFilter, we still run row filtering against the underlying data.  This is mostly because it's hard to actually run the angularJS filter in code given the way we format it (i.e. if you've set your filter to "mapGender | changeCase | translate" then it's hard for us to unstring it all and run those filters synchronously (translate for example, when run from code, is `$translate.instant`).

The best way to do this in code would be to create a dropdown as you're doing, but then use the condition property on the filter to set a regEx that matches the range you want in that particular filter.  I'm not sure we've given all the tools to make that easy - there's no way to tell filtering to put the result of the selected item in the options into the condition property - so you'd need to write some code there.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
