### ISSUE TITLE
Grid Header arrows displays a different icon set (kind of like chinese) 

### ISSUE THREAD

**Issue by SWORDFISH354** [angular-ui/ui-grid#3410]
Hi,

  After setting up the UI-Grid, All of the grid functionalities seem to be working fine except for the icon carets on the header (glyphicons). The icons for sort, ascending, descneding all show up in a chinese language.  Along with UI-Grid, I also have UI-Bootstrap, and Bootstrap 3

![image](https://cloud.githubusercontent.com/assets/7824573/7444710/a7df6136-f1ae-11e4-8257-feab1fe48ea1.png)

![glyphicons](https://cloud.githubusercontent.com/assets/7824573/7444718/d43f17e4-f1ae-11e4-8507-36245fe0378e.png)

**Comment by Dekai** [comment]
I had same issue when I started on using UI-Grid, I copied ui-grid.css to some other directory from its distribution folder and then had the same as you. It's because  it refers to some font files which still locate in the distribution folder. To make it work, it can keep the ui-grid.css in the distribution folder or copy the related the fonts together with ui-grid.css.
I guess you had already fixed this problem since it's one year ago, I posted it here for someone else reference. :)

**Comment by samsfisher** [comment]
Can you please advise how this was solved?

**Comment by Dekai** [comment]
@samsfisher If I remember correctly, the ui-grid.css will refer some icon font and the font file should reside in the same folder with ui-grid.css. I guess you just copied the css file and missed the font file in your project.
You could use Chrome developer tool -> network to check the missing file.

**Comment by samsfisher** [comment]
I figured it out. It's a build related issue. When I included the fonts in
gulp file it worked.

I wish they had a commonJs support in npm build

Thanks
Uma
