### ISSUE TITLE
[Grouping] Initially grouped columns should automatically sort

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ui-grid#3452]
Currently if you provide an initially grouped column, and don't specify a sort on that column, the grouping fails.  This can be seen on tutorial 209 by removing the "sort" columnDef option from the "state" column.

**Comment by AgDude** [comment]
http://plnkr.co/edit/SP0hDC?p=preview

**Comment by PaulL1** [comment]
I've played around with doing this, but it gets quite untidy very quickly.  If you set the sort you also have to set the sortPriority, but the sortPriority is generally fixed through tidyPriorities, so we'd need to find a place to call that.  We're setting the sorts in the columnBuilder, which gets called column by column.  We don't want to call tidyPriorities until all columns are done (otherwise we mess up the priorities if the earlier columns are supposed to be later in the priority order).  There's nowhere easy to call tidyPriorities from.

In theory I could write a queueTidyPriorities function, but I'm not sure it's worth it, and furthermore I'm ending up with a lot of code duplication of the code already in groupColumn.

I guess my question is why anyone would programatically set up grouping without putting sorting on it.  If it's done via the UI then we have it covered, if it's done in code then surely it's reasonable to expect people to do it properly?

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
