### ISSUE TITLE
CSV Import error

### ISSUE THREAD

**Issue by chrislewispac** [angular-ui/ui-grid#3538]
I am attempting to upload a valid CSV filed into the input examples on your tutorials page and getting the following error.

![screen shot 2015-05-20 at 9 47 22 am](https://cloud.githubusercontent.com/assets/10368004/7727208/68ea35da-fed5-11e4-8f69-db6c09137cc3.png)

**Comment by PaulL1** [comment]
That looks like either an error in the csv that you're providing, or an error in CSV.js, which is an external library that we include.  Are you sure your csv is valid?

**Comment by chrislewispac** [comment]
Yes, I have been able to make my CSV work using a different directive and
vanilla javascript.

Chris

**Comment by PaulL1** [comment]
OK, we'll probably be unable to do anything about it without a test case.  Any chance of a plunker or a test csv file?

**Comment by chrislewispac** [comment]
here is a test file

**Comment by PaulL1** [comment]
Did you miss attaching it?  Or perhaps attaching to an e-mail doesn't result it in coming into github?

**Comment by chrislewispac** [comment]
Maybe this will work.

https://docs.google.com/file/d/0B6K4cRlHX5rsRElvVlV1V1pQY3M/edit?usp=docslist_api

**Comment by PaulL1** [comment]
OK, looking at that file, it looks somewhat dubious in terms of how the CSV.js library expects files to be.  The strings aren't surrounded by quotes, which is a bit of a red flag for me.

Nonetheless, it will probably import if it's formatted the way CSV.js expects.

When I try to import it into the tutorial, it gives an `UNEXPECTED_END_OF_RECORD at char 736`, and then also gives me a hint which line that's on by showing the end of the string.  When I import into Excel I can see that there are 4 more columns after the one with `[yds]` in it.  If I add three additional commas onto the end of that line, then reimport the file, it imports that line and starts giving an error on the next line.

I think that the answer is that CSV.js requires every line to have the same number of cells, and whatever has given you that .csv file is being a bit loose with the way it generates .csv.  Unfortunately csv isn't a real standard - it's more a conceptual thing that's implemented by different applications in different ways.

I think the answer is that if you make sure all your lines have the same number of commas it'll probably import just fine.  If I fix the third line as well, then I delete all the other lines, it imports OK enough.  The columns are all too narrow due to having no column defs, so I can't confirm all the data is there, but it looks like it is.

**Comment by c0bra** [comment]
@chrislewispac Did you have any luck getting this solved? Thanks.

**Comment by PaulL1** [comment]
Answer provided, no response for some months.  Closing.
