### ISSUE TITLE
column resize issue on last column

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ui-grid#3612]
This is related to https://github.com/angular-ui/ng-grid/issues/2779
This is my plunker: http://plnkr.co/edit/lO8ewud5X27w3acmUVwR?p=preview

Two problems:
1. The resize border is not aligned with the right edge of the grid.  So it doesn't look good.  I can fix it with css

```
.ui-grid-header-cell:last-child .ui-grid-column-resizer.right {
  border-right: 0px;
}
```
1. The bigger issue.  When you drag the resize bar to the left, the grid doesn't resize with it.  If the grid is meant to stay the same size, the resize feature should be disabled for the last column.

**Comment by c0bra** [comment]
You have scrollbars disabled so you can't see that internally the canvas size is changing. The column is expanding in width but you can't scroll to show it; it's hidden behind your unscrollable viewport.

`border-right` is needed so that the resizing control shows up properly in grids that have scrollbars, unlike yours. Without it there's nothing visually to indicate a control.

**Comment by blowsie** [comment]
On a related note;

I have an issue where you cannot resize the rightmost column when the export menu is enabled.
http://plnkr.co/edit/BR0gn9MEWgfvy7DkviJY?p=preview
