### ISSUE TITLE
Header's calculated height!

### ISSUE THREAD

**Issue by askanhan** [angular-ui/ui-grid#3628]
![ang quest](https://cloud.githubusercontent.com/assets/5607648/7879204/a0446e40-05ee-11e5-8384-ecbbc4d03381.PNG)

This is what happened if i use ng-grid in a SPA written in Extjs. I could get it what happened with the header of the grid. I also could not find where it is calculated in order to change to get a "header with normal width and height".

As a side effect (i think), the rest of the items are also not shown. When i click an item, the list gets also shorter (there stands just 4 entries as u can see in the picture)

What should i do?

ps: ui-grid current version and extjs4.1

**Comment by c0bra** [comment]
1. When you say "current version" do you mean RC.21 or the latest unstable? You could open up ui.grid.js/ui.grid.min.js and paste the version line here.
2. Do you get the same result if you turn filtering off?
3. Any other details on your grid, or info on how one might reproduce this, perhaps in a plunker?

We used to have problems with header height growing uncontrollably but they should have been fixed quite a long time ago.

**Comment by Phalynx** [comment]
I can confirm this also. Using RC.21: ui-grid - v3.0.0-rc.21-15ee480 - 2015-06-02

It happens also by using the unmodified tutorial 101.

**Comment by askanhan** [comment]
1. 
/*!
 * ui-grid - v3.0.0-rc.21-57f556d - 2015-05-28
 * Copyright (c) 2015 ; License: MIT 
 */
2. Yes
3. I could fix it by adding this css:
.ui-grid-header-cell-wrapper{
  height: 50; // or any other fixed size.
}
And if the size is about 20 and 30, the checkboxes in selection-column became also not approriate for the other rows. You click second checkbox and third item is selected.

**Comment by c0bra** [comment]
Please try the latest RC (22) and see if the issue goes away. There's been lots of fixes across the board.

**Comment by ajkavanagh** [comment]
Just out of interest, I had something identical happening to me.  I had `<!DOCTYPE html5>` as my document type, which has the 'happy' side-effect of allowing iFrames to grab as much vertical space as they like (which is why I had it set that way).

However, this broke the ui-grid header height algorithm which started calculating insanely large sizes.  Setting the document back to ` <!DOCTYPE html>` solves the header height problem (for me), and then I just wrapped the iframe in a `<div style="height: 1000px;">` (or whatever - I did it with a class) and that enabled a sane amount of iframe (which is otherwise stuck on 155px high).
