### ISSUE TITLE
Sort in grouped grid is not working as expected

### ISSUE THREAD

**Issue by yuanda** [angular-ui/ui-grid#3667]
In tutorial [209_grouping](http://ui-grid.info/docs/#/tutorial/209_grouping), the sorting is not working as expected. In the demo grid, if you sort the balance column ascending, none of the grouped rows would change, but the sorting was actually taking effect on the rows under each grouped rows. 

![2015-06-01 16_00_20-clipboard](https://cloud.githubusercontent.com/assets/2967550/7938531/09fb0916-0914-11e5-8af2-0dc54ff86614.png)

**Comment by PaulL1** [comment]
That's actually exactly as expected.  The grouped columns are always sorted first, otherwise the grouping wouldn't work.

**Comment by yuanda** [comment]
In the above example, if there is anyway to set the sort priority of grouped column lower than the balance column? 

What I'm expecting is the row 'Wisconsin(10)' will be above of 'Wyoming(10)' when I set balance to sort ascending, since the balance of Wisconsin ($2,241) is lower than that of Wyoming's ($2,558). 

![image](https://cloud.githubusercontent.com/assets/2967550/7943629/b3014fe2-0933-11e5-9ccf-77eb08fb0ed4.png)

**Comment by PaulL1** [comment]
No, the grouping has a sort inside it - in order to group it must first sort.  So the state sort must be the high order of the sorting.  TreeBase actually has a treeSort capability inside it that maybe could be used in that way, but it hasn't been configured to do that.

**Comment by yuanda** [comment]
OK, thank you very much.

**Comment by eduiagami** [comment]
Hello, do you have a solution for this situation? I agree with Yuanda. I expected the same behavior as he informed.

Can you please help me to solve this issue?

I will appreciate a lot!

Thanks.

**Comment by GilHelfgott** [comment]
As far as I understand the functionality of sorting while grouping is enabled, I also agree with @yuanda  and @eduiagami that the resulted behavior is non-intuitive. 

I expected that sorting will be first applied on the aggregated value, and then (maybe), internally, in each group - but again, this may not be the standard in data grids. 

Still, +1 for providing a way to support this.

**Comment by NirHemed** [comment]
+1 for what @GilHelfgott  said.

**Comment by DivakarGit** [comment]
Hello, do you have a solution for this situation yet? Any Hacks to achieve this functionality?

**Comment by MishaTornes** [comment]
Looking at [http://ui-grid.info/docs/#/tutorial/320_complex_grouping]
It also seems the sorting by char instead of value. 
Is it a setting or a new issue?

![image](https://cloud.githubusercontent.com/assets/2124154/18649255/8bb84aec-7e8c-11e6-9029-8cbd594f54bf.png)

**Comment by PaulL1** [comment]
It sorts based on column type. If you set column type to number (or was it numeric?) it'll sort numbers. Otherwise it sorts char.

Sent from my iPhone

On 20 Sep 2016, at 9:15 AM, MishaTornes <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at [http://ui-grid.info/docs/#/tutorial/320_complex_grouping]
It also seems the sorting by char instead of value.
Is it a setting or a new issue?

[image]<https://cloud.githubusercontent.com/assets/2124154/18649255/8bb84aec-7e8c-11e6-9029-8cbd594f54bf.png>

-

**Comment by MishaTornes** [comment]
Hi @PaulL1,
How do you set the column type? 
I can't find a reference or example in the docs...

**Comment by PaulL1** [comment]
Gridoptions.column.type I think from memory. It's in the doco somewhere and I thought in one of the examples.

Sent from my iPhone

On 20 Sep 2016, at 11:37 AM, MishaTornes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @PaulL1<https://github.com/PaulL1>,
How do you set the column type?
I can't find a reference or example in the docs...

-

**Comment by MishaTornes** [comment]
Thanks @PaulL1 finally found it here [http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef].
GridOptions.columnDef.type
States: "Add this only if the grid guessing is not to your satisfaction."

**Comment by RajKann** [comment]
Hi @PaulL1,

I am having similar problem in sorting on group column too (angular-ui-grid v3.1.01). In my case the group column is a mix of number and text and also I have the flexibility of changing the grouping dynamically using a button. So I'll be calling that group by function after all my json array is updated. The group columns data from json will look like {'1-Purchasing, '2-sales, '14-Marketing', '1401-Manufacturing', '20-HR', '410-Admin' }

I wanted to see the final group sorting on the grid as {'1-Purchasing, '2-sales, '14-Marketing', '20-HR', '410-Admin', '1401-Manufacturing'}

I even created a hidden grid column and placed the number part and tried to sort that column because the type: 'number' on the department name did not group by instead messed up the grid by repeating the deptName and EmplyeeName

`//group by function
{
$scope.gridApi.grouping.clearGrouping();
$scope.gridApi.grouping.groupColumn('DeptName');
$scope.gridApi.grouping.groupColumn('EmployeeName');
$scope.grid1Api.grid.sortColumn('DeptNo', $scope.uiGridConstants.ASC, false);
}`

Any help will be appreciated.

**Comment by box5games** [comment]
+1 for what @GilHelfgott said.

**Comment by dasariramacharan** [comment]
hi @RajKann 

you would be required to implement custom sorting
refer http://ui-grid.info/docs/#!/tutorial/102_sorting
