### ISSUE TITLE
[Grouping] aggregate columns with invalid values show "undefined" inside the row

### ISSUE THREAD

**Issue by valepu** [angular-ui/ui-grid#3689]
Hello,
I have noticed that when you use an aggregation function on a column with invalid values (for example "Average" on a column which contains only non numeric fields. It works fine if only some fields are non numeric) then in the cell it will appear, in the case of average, "avg: undefined" (this also happens with other functions which only work on numeric values).
I think it's more useful, UX wise, to show either an empty string or an "Invalid" label (for example "No valid values found" instead of "avg: undefined") or let us chose what to show when invalid fields are found, just like the recently implemented "groupingNullLabel" option.

To reproduce this issue:
Use this plunker http://plnkr.co/edit/I4hNKy6odqLCbCbl75vI?p=preview
1. open the menu for any column
2. click on "Group"
3. open the menu for a different colum than the one used for grouping
4. click on "Agg: Avg"
In the fields of the column will appear the text "avg: undefined"

This happens for all the aggregation functions that expect numeric values (which means all of them except Count)

**Comment by PaulL1** [comment]
This could be done, although to my mind it indicates a coding problem on the behalf of the user - if they're aggregating a column then they should be sure that the column includes aggregate-able values, otherwise the result they'll get will be unexpected.  This is particularly true, for example, for averages - you have to know whether the non-numeric value was included in the count or not.

If we're saying that we'd like to aggregate a column that has mixed text and number values, then I think we should build and document explicit rules for that aggregation - for Max we'd just ignore non-numeric values, for avg we'd treat them as zero or ignore them and so on.

My preference is to leave it as it is, as that forces the user to fix their data, but I'm not particularly strong in that opinion.

**Comment by valepu** [comment]
While i can agree with you about taking care about data, i can think about a some cases where it could be useful to have some kind of different treatment on "invalid" data, taking into account that In some cases you have no control over the input (let's say, for example, some kind of sensor that gives you no output if data is not available):

1. When there are empty values: sometimes you might have a sparse matrix, though instead of 0 values are null or empty string, probably because 0 and empty assume different meanings in your system

2. When there are text values for not available data: in some cases you have N/A or some other label instead of a value, when data is not available or not applicable for a certain row.

I might suggest, if you think it's feasible, to add an option (either global or for each row, probably global is simplier) that tells the aggregation functions how to handle invalid numeric values, the option might have these choices:

IGNORE: Ignores invalid rows, that is, if you have a column with 
2
3
NA
4

Then average will return 3 (2+3+4)/3=3

TREAT_AS X: treats invalid data as a specific number (defaults to 0, but can be changed). In the example above it will show 2.25 as average (assuming you are using 0 as value) because it will do (2+3+0+4)/4=2.25

WARN: if there is at least 1 invalid value then it will show a warning in the row. In the example above it will show something like "Invalid or empty data found in group". It should be possible to specify a custom message

CUSTOM: lets you specify a function to be called to treat invalid data, the function might accept the value as argument. This might replace "TREAT AS X" as you can implement a similar functionality through a custom function

The default behavior for ui-grid could be WARN (better than "Avg: undefined" at least).

I know it might be too big of a feature for this issue but well i had this idea and i thought it was worth suggesting

**Comment by AgDude** [comment]
I haven't look at this in detail yet, but I am inclined to agree with
Paul.  You should be able to accomplish what you want with a custom
aggregation finalizer function.

**Comment by AgDude** [comment]
This issue is really about different data cleaning for numValue, which occurs within the aggregate function in tree-base. Currently this is simply ```Number(fieldValue)```, which I would like to keep as the default. I would be open to a pull request which added an option for a different function for coercing a number from the cell.

All of the functionality described by @valepu could be accomplished using a custom aggregation function. Look at the complex grouping tutorial for some examples of how to stack aggregation functions, or use an existing aggregation function as a "helper" inside of another one.

**Comment by valepu** [comment]
While i agree on what you said, I still think that "avg: undefined" is a bit ugly to see

I'll see what i can do if i can manage to make a pull request to add a handler function to aggregation

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
