### ISSUE TITLE
pagination and controls

### ISSUE THREAD

**Issue by gindij** [angular-ui/ui-grid#3702]
Hi,

I have enablePaginationControls:  true, paginationPageSize: 25, and paginationPageSizes: [25,50,75]. I have ui.grid.pagination in my app dependencies. I have the ui-grid-pagination directive in my html. When the grid renders, though, the dropdown for the pagination page sizes displays (probably the default) 250,500,1000... Does anyone know why this might be/how I could fix this?

Thanks.

**Comment by PaulL1** [comment]
It seems to be working in the tutorial: http://ui-grid.info/docs/#/tutorial/214_pagination, and when I put in different values it picks them up: http://plnkr.co/edit/DO7E9Vq521d9maucDfrs?p=preview

I can only assume there's some sort of typo or inconsistency in your code, or that you have a very old version (since pagination hasn't been changed for a long time).  Perhaps a plunker to demonstrate your issue?

**Comment by PaulL1** [comment]
Information sought, and no response for some months.  Closing.
