### ISSUE TITLE
"CheckBox Click" doesnt work using Protractor in FireFox 

### ISSUE THREAD

**Issue by prabhu-telsiz** [angular-ui/ui-grid#3730]
Hi,

![screen shot 2015-03-27 at 4 33 42 pm](https://cloud.githubusercontent.com/assets/9666941/8044231/2d15697a-0de0-11e5-9f91-0fc17e267063.jpg)

This is my table.
Im trying to click the checkbox in the left of each row.

PROTRACTOR CODE(Protractor 2.0, Firefox 38.0.1)
// Code is from ng-grid/test/e2e/gridTestUtils.spec.js with little modification to point the .ui-grid-pinned-container-left

this.checkbox_datacell= function( gridId, fetchRow, fetchCol ) {
        var row = gridUtil.getGrid( gridId ).element( by.css('.ui-grid-pinned-container-left')).element( by.css('.ui-grid-render-container-left')).element( by.repeater('(rowRenderIndex, row) in rowContainer.renderedRows track by $index').row( fetchRow )  );
        return row.element( by.repeater('(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name').row( fetchCol ));
    };

checkbox_datacell('tableID',0.0).click();

The code works properly with CHROME browser.
But the same code when I run with Firefox, the checkbox is not getting clicked.

Does gridTestUtils.spec.js not work with firefox or something. Can someone help me with it.?
Thanks.

**Comment by PaulL1** [comment]
Protractor is notoriously flaky, I still haven't got the test utils working for the editable grid (which is why most of the features don't have e2e tests yet - 201 is the first of the features and I haven't gotten it working).

Things I can suggest would be:
1.  Some of the api to protractor is promise based, so sometimes when you think you have an element you actually have a promise that will eventually resolve to an element, and sometimes this causes behaviour you don't expect.  Having said this, the click handler should be aware of that and should work cleanly, but it may give you grief in trying to debug
2.  I'd be looking to see what the element is that was returned by gridUtils - write out the contents of it or something to see if it is actually a checkbox.  Perhaps there's a timing issue going on in Firefox?
3.  Sometimes putting a wait into the code can make things work, and this would tell you if you have a timing issue (I wouldn't leave the wait in the code, just use it to diagnose the problem).  I think it's browser.sleep that you use to do a wait in protractor, memory is failing me.

**Comment by prabhu-telsiz** [comment]
OK. Thanks. I will try and let you know.
