### ISSUE TITLE
Unable to disable row selection when using enableRowHeaderSelection

### ISSUE THREAD

**Issue by pedroclayman** [angular-ui/ui-grid#3743]
It is not possible to disable row selection effectively when enableRowHeaderSelection. In my opinion it should be possible to disable the selection row header also after the initialization. 
http://plnkr.co/edit/hKB1aqD3KbLErTiEF3c4?p=preview

**Comment by benoror** [comment]
Maybe related, it's also not possible to **toggle** `enableRowHeaderSelection`, I would expect to hide/show the whole selection column  see example: http://plnkr.co/edit/48GOvYLbfXcL0ITB2XzQ?p=preview

**Comment by benoror** [comment]
Still haven't found a fix for this.

The only way to completely disable row header selection is to remove `ui-grid-selection` attribute from the directive markup, but there isn't a clean way to do this on demand.

Any help would be appreciated!

**Comment by imbalind** [comment]
If I get it right, what you need can be accomplished by using [`isRowSelectable`](http://ui-grid.info/docs/#/api/ui.grid.selection.api:GridOptions#properties_isrowselectable).

I'm closing this since the issue the OP opened was not a bug.

@benoror if you think `isRowSelectable` doesn't suit your needs, I'd suggest you try opening a question on Stack Overflow. 

In order to ease the maintainer's job, we're asking to create new issues only when you have solid proof that there is a bug in the code or if you want to propose an enhancement.

**Comment by benoror** [comment]
@imbalind totally agree, issues should be reserved for bug reports and feature requests :+1:  (I actually have some [canned responses](https://gist.github.com/benoror/9b93667059bfe6ff5c02) I use for a project I contribute to).

The thing is that **ui-grid docs are sometimes vague**. I didn't notice `isRowSelectable` before. Still I don't get why setting `enableRowSelection` to `false` for the whole grid doesn't work, **to me that looks like a bug**.

Anyway this workaround does the trick for the time being, I appreciate your help.

Cheers and happy holidays! :santa: :snowman: :smile_cat:

**Comment by mukulchakane** [comment]
i had to faced same issue in IE11. i need to double click the cell to edit whereas in chrome and firefox it works on single click
can someone please help with this issue of ui-grid ????
