### ISSUE TITLE
uigrid (in cellnav.js) always just request focus when the directive uiGridViewport is constructed

### ISSUE THREAD

**Issue by jcompagner** [angular-ui/ui-grid#3896]
ui-grid is just one of the components on our page (could even be more then 1 ui-grid) 
but we do call focus() on a certain element, but the focus is then most of the times (depends on timing) suddenly transferred .
Its then on the div with the class "ui-grid-focuser" this is because in cellnav.js  on line 851 there is always a focus request call:  uiGridCtrl.focus();

ui grid should not do that by default when it is constructed, only when it somehow already had focus or focus was request to it by the developer itself.

Now the focus is really forced to it when loading (and for me at that time the grid is even not filled its empty)

**Comment by JLLeitschuh** [comment]
I found this bug myself while working through adding screen reader accessibility to cell nav.
It is caused by this line here: https://github.com/angular-ui/ng-grid/blob/e9a6d4eba67dba23c42b54b23054c048cf9d8ebc/src/features/cellnav/js/cellnav.js#L851

I was planning on fixing it in my accessibility push.
