### ISSUE TITLE
When clearing filter with "x" key, event filterChanged fires but not rowsVisibleChanged

### ISSUE THREAD

**Issue by valepu** [angular-ui/ui-grid#3901]
see this plunkr: http://plnkr.co/edit/NPazbil7fCU39SgHviDf?p=preview

To test it:
1) Open the javascript console while on the page
2) Clear the "Company Name" filter by clicking on the x next to it
Result:
on the console you will see "Event fired: filterChanged" but not "Event fired: rowsVisibleChanged"

**Comment by jjcad** [comment]
+1

**Comment by jjcad** [comment]
I did notice that clearing filters in either the column header or using "Clear All Filters" in the menu does kick off the 'rowsRendered' event.

It seems like the issue might be with `Grid.prototype.setVisibleRows`, which only raises a 'rowsRendered' event.  Since it's responsible for setting the visible rows, it seems sensible that it should also let everybody know that the visible rows changed instead of only letting everybody know that the rows are rendered.

**Comment by dlgski** [comment]
applied PR to fix this v3.2.10
