### ISSUE TITLE
Filter by empty value

### ISSUE THREAD

**Issue by mc0re** [angular-ui/ui-grid#3912]
I have a column, which contains some strings, but could also contain an empty string.
I define a filter like this:
`filter: {
    type: uiGridConstants.filter.SELECT,
    selectOptions: []
}`
Then I fetch unique values for this column, and finally do the following:
`column.filter.selectOptions = values
    .map(function (v) { return { value: v.value, label: v.translation ? v.translation : 'Empty' }; });`

As a result, I get a dropdown with an empty line (inserted by UI Grid, "no filter"), line saying "Empty", and some values.

Now the issues:
1) It is arbitrary, whether upon table loading an empty option or "Empty" option is selected.
2) Selecting an "Empty" option in the dropdown has the same effect as selecting an empty option - no filter.

How do I properly filter by empty values?

**Comment by jlengwork** [comment]
I know this is kinda old, but I had to find a similar solution this week.  Using a dropdown is correct, all you would need to do is set a condition function as such:

```
column.filter.condition: function (searchTerm, cellValue) {
        return searchTerm == 0 || searchTerm == null || (searchTerm == 1 && cellValue != '') || (searchTerm == 2 && cellValue == '');
      }

```
This issue is simiilar to: https://github.com/angular-ui/ui-grid/issues/1652.  I posted a few more details on my implementation there as well.
