### ISSUE TITLE
Correct grouping is only triggered by explicit sorting

### ISSUE THREAD

**Issue by dsaf** [angular-ui/ui-grid#3930]
To reproduce:

1) get the official example at http://ui-grid.info/docs/#/tutorial/209_grouping

2) remove all the explicit sorting configuration:
http://plnkr.co/edit/Y4UTFVrlyu72SPE0CV0m?p=preview

3) observe lots of single-row groups:
![image](https://cloud.githubusercontent.com/assets/3845650/8501934/2f8dac82-21a2-11e5-8361-75fc6116a0f9.png)

4) trigger explicit sorting by clicking any header:
![image](https://cloud.githubusercontent.com/assets/3845650/8501937/4753f204-21a2-11e5-856d-100c3fbca137.png)

5) notice correct grouping was triggered (notice the difference in scrollbar scale between the screens).

**Comment by dsaf** [comment]
Also it would be great to have a config option to expand groups by default. Should I create a separate request for that or it is already available?

**Comment by PaulL1** [comment]
Yes.  You have to explicitly set the sorting as part of configuring the grouping.  This is a documented expectation.  Why would you want to set default grouping but not set default sorting?  Since doing so would be a coding error, it seems like as soon as you tested it you'd realise your mistake and fix it?

**Comment by dsaf** [comment]
@PaulL1

> This is a documented expectation.

I have read the tutorial more carefully, and you are correct in noticing that it is documented.

> Why would you want to set default grouping but not set default sorting?

Because this time I was working on my GUI incrementally from scratch, rather than copy-pasting and editing a demo.

I can give you three examples of top collection manipulation frameworks that do not require sorting while grouping:

http://underscorejs.org/#groupBy
https://msdn.microsoft.com/en-GB/library/system.linq.enumerable.groupby(v=vs.90).aspx
http://www.w3schools.com/sql/sql_groupby.asp

If you want something closer to GUI then have a look at another well-known grid:

http://demos.telerik.com/kendo-ui/grid/aggregates

> Since doing so would be a coding error, it seems like as soon as you tested it you'd realise your mistake and fix it?

This is not a coding error or a mistake on my behalf, but rather an unobvious design decision that does not follow https://en.wikipedia.org/wiki/Convention_over_configuration

Besides that the API doesn't guide me to fixing the "mistake / error" - it just puts the grid in an unexpected state. Angular on the other hand would throw an exception if I misspell a module name (instead of just injecting ```undefined``` or even ```{}```).

Regardless, this is no longer a problem for me, I just wanted to point this out as a feedback. Also it looks like a top-notch grid in the making, so I am too grateful to argue further. Feel free to close this issue if you feel that it's a right thing to do.

Thank you.

**Comment by PaulL1** [comment]
It has been raised before, the main issue is that it's hard to automatically apply the sorting to the default configuration in the same way that it's applied to user created configuration.  There isn't an obvious place in the code where we'd apply that configuration.  Hence why it hasn't been done.

So yes, it's a good idea, but every time I look at it I find that a) it's a bit harder than I'd hoped, and b) it's really a one time issue for each person who encounters it - once they see what's going on then they code in the sort and things work out fine - so that sort of eats into the impetus to do something about it.

**Comment by dsaf** [comment]
I understand what you mean. Maybe the most pragmatic temporary solution would be highlighting the reliance on sorting in the documentation:

```
<div class="alert alert-warning">
<strong>Note:</strong> Grouping leverages the sort functionality, allowing a user to change the sort order or use external sort functionality and have the resulting list grouped. A column(s) that is marked as being grouped is always moved to the high order of the sort priority, as the data must be sorted to permit grouping.
</div>
```

Angular documentation (over-)uses alerts to highlight problems quite a lot e.g. https://docs.angularjs.org/guide/directive

**Comment by PaulL1** [comment]
Good suggestion - this would make it clearer for new users.

**Comment by nupur2710** [comment]
How to sort manually in this case?
