### ISSUE TITLE
Grouping header label is not displayed in ui-grid if we use cellTemplate with dropdown values

### ISSUE THREAD

**Issue by ravivantaku** [angular-ui/ui-grid#3957]
http://plnkr.co/edit/Fd83R3gM8DZcF63x6WtI?p=preview

I have modified the plunker which is given in grouping examples in ui-grid. 
http://ui-grid.info/docs/#/tutorial/320_complex_grouping
In the above plunker i changed the gender field editableCellTemplate into cellTemplate with dropdown values then the gender field grouping header label is not visible. In columnDef's cellFilter is not working if we place cellTemplate in that column but works fine for editableCellTemplate property for the same column.

Give me any solution for this. Thanks in advance.

**Comment by PaulL1** [comment]
You seem to have changed the normal cell template to a dropdown, rather than the editable cell template.  The group headers include the totals usually, so they don't match the values in the dropdown.  You can probably fix this by using the `customTreeAggregationFinalizerFn` as described in the 209 tutorial, but really you shouldn't be setting the default template to be editable.  I'm not sure what behaviour you'd expect if someone changed the dropdown on a group row - would all the items under that grouping change gender?

**Comment by ravivantaku** [comment]
Thanks for reply.
Actually my requirement is i need to give a option to select values as  drop downs and textboxes in each row. If i use editableCellTemplate i need to double click that column to select value so i used cellTemplate instead editableCellTemplate. The cellTemplate dropdown values are coming form service as array of objects. If i use cellTemplate with dropdown element in a column and i grouped that column then that groupeHeader is not display the dropdown value as a header label it just display the dropdown field. I followed the given example in the ui-grid examples( http://ui-grid.info/docs/#/tutorial/209_grouping ). I changed the previous plunker to update with customTreeAggregationFinalizerFn as mentioned above comment. I don't need to edit groupedHeader, i just want to display the selected dropdown values as groupedHeader. 

The updated plunker is here 
http://plnkr.co/edit/RK4O0R0mYcFrctCWcaCf

Thanks in advance.

**Comment by PaulL1** [comment]
If you use editableCellTemplate and editOnFocus you don't need to double click.  I still don't quite see what you're trying to achieve, you're not showing the dropdowns on the rows themselves, you're only showing them on the group header.  What do you expect to happen when someone selects a value in the dropdown?
