### ISSUE TITLE
conditional row selection on a large dataset causing crash

### ISSUE THREAD

**Issue by sdum** [angular-ui/ui-grid#3962]
Hi,

I have a set of 3000 rows in my ui-grid. When i get datas, i have to select rows depending on a boolean attribute. I use a simple loop to test and select rows :
```javascript
for (i = 0; i < $scope.aDatas.length; i ++) {
    if ($scope.aDatas[i].bDisplayOnMap) {
        $scope.gridApi.selection.selectRow($scope.aDatas[i]);
    }
}
```

This code is causing the crash of the browser every time. 

My context is angular 1.3.12 with ui-grid 3.0.0-rc20

Please, is there another way to achieve this ?

**Comment by JLLeitschuh** [comment]
Can you provide a plunker demonstrating your problem?

**Comment by sdum** [comment]
Hi,

Finally, i solved the problem by looping over the rows directly :

```javascript
for (i = 0; i < $scope.gridApi.grid.rows.length; i ++) {
    if (true === $scope.gridApi.grid.rows[i].entity.bDisplayOnMap) {
        $scope.gridApi.grid.rows[i].setSelected(true);
    }
}
```

I think that using selectRow(entity) method, the component has to look for the row corresponding on the entity, so it could be heavy on a large dataset.

**Comment by nkoterba** [comment]
This issue is similar to #4457.  Namely that trying to select *multiple* rows based on some row property can be badly performant on large data sets due to the fact that `$scope.gridApi.selection.selectRow` iterates through all the internal rows for **each** select.

In #4457, I propose creating a `selectRows` method that would in essence do what @sdum did in the method above: loop over the internal rows and set rows to selected based on some user defined property or attribute (or maybe even a callback).

@sdum original implementation is O(n^2) while his second approach is O(n) which on large datasets will have a significant speed improvement.

I would like to contribute to creating such a `selectRows` method but am under deadline pressure at the moment. Hopefully, once that clears I can help out.
