### ISSUE TITLE
Grid menu doesn't use column definitions to take translations

### ISSUE THREAD

**Issue by mahpour** [angular-ui/ui-grid#3965]
I have 2 languages enabled in my app through angular-translate module. when I switch the language I can see the column headers change but the grid menu on the corner is not showing the translated version of displayName property in columnDefs array. 

```json
columnDefs: [
                { displayName: 'GRID.NAME', field: 'a', headerCellFilter: 'translate' },
                { displayName: 'GRID.GENDER', field: 'b', headerCellFilter: 'translate' },
                { displayName: 'GRID.COMPANY', field: 'c', headerCellFilter: 'translate'}
            ]
```
My translation json:

```json
{
"GRID": {
        "NAME": "Name",
        "GENDER": "Gender",
        "COMPANY": "Company"
    }
}
```

Output:

![image](https://cloud.githubusercontent.com/assets/202065/8625505/41294238-270d-11e5-9826-0ea91578fd4c.png)

**Comment by PaulL1** [comment]
The grid menu will only translate if you provide a filter for it.  Your headers are presumably translating through providing a cellHeaderFilter, you also need to provide `gridMenuTitleFilter`.  http://ui-grid.info/docs/#/tutorial/121_grid_menu

**Comment by mahpour** [comment]
Thanks you, that worked. However should it not automatically follow whats offered in the headers? I agree with this approach when we define custom menu items but for those derived from column def set I think it should follow same filter for consistency.

**Comment by PaulL1** [comment]
Yes, but the format for the filter is different, so it cannot.  The header filter is an angular UI filter - so you can chain ' translate | someOtherFilter'.  We cannot call that synchronously to populate a menu - the menu filters are called on the text itself synchronously.  We could make column hide/show menus different from all other menus, but then that's another source of inconsistency, so doesn't really fix the problem.

**Comment by mahpour** [comment]
I haven't gone through the source code but if its iterating through menu titles, can it not run a <code>$filter(colDefs[idx].headerCellFilter)(colDefs[idx].displayName)</code> on those which have any filters defined before it runs the <code>gridMenuTitleFilter</code> function over them? Maybe my thoughts are not generalized to cover all scenarios... this is not a major issue though. I'm sure people will find the right way to fix it eventually, may be by reading this thread :-)

**Comment by PaulL1** [comment]
Hmm.  Possibly.  I first ran into the filter problem in exporter, and the problem in exporter was both syntax and the fact that it had to be synchronous - since we were putting it into a csv or pdf immediately, I needed a synchronous filter call.  I may not have revisited that assumption when doing the grid menu - because arguably that could be asynch, and if the syntax you suggest works to call a chained filter, then yes it would work.

Arguably if I played with promises and messed around enough, I could get that to work for the exporter filters as well, and that would be a much better outcome.  There's a bit of work in that though.  I'll leave this open and look at it when I have time, which unfortunately will be about Christmas at the moment.

**Comment by mahpour** [comment]
Much appreciated! keep up the good work!

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.
