### ISSUE TITLE
Including column footer option when exporting to csv?

### ISSUE THREAD

**Issue by sadeks** [angular-ui/ui-grid#3967]
Is there an option to include the columns' footer while exporting to csv? I searched in the docs and found nothing.
I used this tutorial http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex to implement the exporting to csv functionality.

Thanks and great work!!

**Comment by PaulL1** [comment]
No, there is not an option for this.

**Comment by PaulL1** [comment]
This is a useful request, but not really in the current roadmap.  We have far too many good ideas in the repository already, giving the impression that we have a project riven with defects.

Accordingly, I am leaving the enhancement tag on this, but closing it.  If someone would like this functionality, we'd welcome a pull request that adds it.

**Comment by normkatz** [comment]
I would love to have this functionality.  Alternatively, perhaps you can provide a code snippet that we can use to"append" a line of text to the data object that is being written to the csv file that gets downloaded to the target.  Since the footer's going to be the last line of text in the file, we can probably fudge something pretty easily while waiting for a formal release with this features.  Much obliged.

**Comment by rodrigoimenes** [comment]
@PaulL1 Any update about this?

**Comment by MSIslam** [comment]
@PaulL1 @sadeks Did you guys figure if there is any option to export the column footer now?

**Comment by jonteferm** [comment]
I would be grateful for this possibility

**Comment by RubiconIII** [comment]
Please can we include this feature?  Seems like essential functionality to me...

**Comment by lukerh18** [comment]
Would love to get this feature pushed through. Is there any update on this front, where it is on the roadmap?
