### ISSUE TITLE
Improving user experience - Moving filter section in column menu or make it available in other dropdown

### ISSUE THREAD

**Issue by aravindtrue** [angular-ui/ui-grid#3989]
I've started using it for past few weeks, it has really improved a lot with such a great performance. I would like to share few thoughts on filter section, which works great but need few improvements on look and feel. Right now, all filter options are displayed right below the column header and it will be visible all the time. As a user, I want to see it whenever I want to filter, is there any way to move the complete filter section in column menu i.e., after sort options?

Also, I was trying to position the filter section so that I can make it available in a dropdown on user demand. But this breaks the grid header when we have horizontal scroll bar.

http://stackoverflow.com/questions/31422422/angular-ui-grid-moving-filter-section-in-column-menu

Do you have any improvement plans for filter section? Can you please help to improve the look and feel?

**Comment by shivarajskit** [comment]
I am also looking for the same. It will be nice to have this feature on top of awesome existing features of UI Grid.

**Comment by techiemanas** [comment]
This is a nice to have feature , i was also wondering fro this sometime around.

**Comment by Dinesh-Talreja** [comment]
+1

**Comment by rameshpadithurai** [comment]
Even i have such requirement for one of my project, Can any one help us out on this.

Thanks in advance

**Comment by Sweta-Agnihotri** [comment]
+1

**Comment by dipabhatt** [comment]
+1

**Comment by nbdesai** [comment]
+1

**Comment by PaulL1** [comment]
The filter section is switchable, so you can easily add your own UI extras (perhaps in the grid menu) to show and hide the filter boxes.  I think one of the tutorials even demonstrates this.  Would this be sufficient for your needs?  If not, you can use custom menu items on the columns to provide custom filter boxes.  I have done this in one of my applications because I wanted to use modal windows to set the filters, and it works just fine.

**Comment by aravindtrue** [comment]
@PaulL1 Can you please provide me a Plnkr or any demonstration link? It'll be very helpful for me to analyze.

**Comment by KulPrashant** [comment]
This will be really very useful, I can see that it is added as milestone, could you (@swalters) please let us know if you have approximate time frame to release this feature...Thanks..

**Comment by vipsingh1** [comment]
It would be great if we get this feature available in next release.

**Comment by webiks** [comment]
I've got a prototype working. Is there anyone working on this one? Or can I send a PR for this?

**Comment by swalters** [comment]
@webiks can you post some screenshots here of what you've done?  thanks.

**Comment by webiks** [comment]
It might take a while. It's in the office.  In the meantime, I'm having problems running the dev environment. #4071.

**Comment by webiks** [comment]
There you go:
http://plnkr.co/edit/HVohvjElaMoJU3kFKMjx?p=preview

**Comment by aravindtrue** [comment]
@webiks - The look and feel is really great! I'll try it out in my application and scale the performance.

**Comment by webiks** [comment]
It's hardly finished, but would be great to get feedback on the go., Thanks

**Comment by webiks** [comment]
You can now choose between multiple selection and singular selection.

**Comment by orlandumike** [comment]
I think that it would provide a better UX and that's what we are looking for.

Our UX team was proposing to have some kind of filter icon beside the column name that would expand a hidden section contailing the filter. Having the normal auto complete text or a dropdown or a customer filter like this would be nice.

![image](https://cloud.githubusercontent.com/assets/3011084/12777896/e447ab12-ca5f-11e5-80a8-d425c7acdbef.png)

The filter icon could have 2 versions: (ex: one empty and another filled)
- Not applied (so that we can make it pop and add a filter)
- Currently applied (indicator that a filter is appled and also provide the way to change it.

Clearing the filter should probably be part of the expanded section.

Good work with the grid guys by the way!

**Comment by swalters** [comment]
@yccteam has a branch that provides a similar ui.  It will be implemented outside the core repository.  https://github.com/angular-ui/ui-grid/pull/4108

**Comment by orlandumike** [comment]
Ok, but will it ever make it into the core?

At the moment, I'm adding a filter button as a custom filter that open a dialog  and afterward update the term of the column.

**Comment by sryzycki** [comment]
Hi and thank you for this amazing Angular module. I understand that you guys are extremely busy but I would like to still ask this question:
What's the latest on having column filters inside of a dropdown?

Happy New Year!

**Comment by AnushaputtaUI** [comment]
Any Idea on how to achieve the above design using UI-grid

**Comment by betsydupuis** [comment]
@AnushaputtaUI 

I think that it could be accomplished with a filtered search field like the example below.

<img width="670" alt="screen shot 2017-12-01 at 8 38 25 am" src="https://user-images.githubusercontent.com/2096627/33487508-127108f0-d673-11e7-8241-5c915acc8a77.png">

Selections could then be displayed as a list of tags like `Appliances : Toaster`, `Appliances : Refrigerator`, `Appliances: Stand Mixer`

**Comment by AnushaputtaUI** [comment]
I guess my question is I need some filter icon for each column and when I click on the icon it should toggle the filter widget on each column.
