### ISSUE TITLE
Documentation Tutorial Broken

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ui-grid#3996]
The collapse button gone, header menu gone, basically un-usable tutorial now including:
209,215,216,319,320

**Comment by aarosil** [comment]
I see the same, none of them load for me at all.  Same with the plunkrs.  I'm guessing might be something to do w/ the release?

**Comment by asakalou** [comment]
Hello guys, 
That's what I see on the page http://ui-grid.info/docs/#/tutorial/209_grouping

Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ui.grid.grouping due to:
Error: [$injector:nomod] Module 'ui.grid.grouping' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

We really need your demo pages :)

**Comment by swalters** [comment]
yes, we know and are fixing it
