### ISSUE TITLE
Grid gouping and sorting 3.0.1

### ISSUE THREAD

**Issue by arnoldsimha** [angular-ui/ui-grid#4004]
Hi,
I have a grid with grouping. the object in array is:
```
{
 name: "a",
group : "1"
 index: 2
},
{
 name: "b",
group : "1",
 index: 2
},
{
 name: "c",
group: "2",
 index: 1
},
{
 name: "d",
group: "2",
 index: 2
},
```

As you can see I want to group by "group property but sort the groups by index. 
Your help will be appreciated.

**Comment by PaulL1** [comment]
You should be able to set grouping by the group, and then sorting by the index.  The tutorials may help you in this.

**Comment by arnoldsimha** [comment]
I locked at the tutorials. In column defenition I can set name
```
{
              name: "group",
              grouping: { groupPriority: 0 },
              sort: {
                  priority: 0,
                  direction: uiGridConstants.ASC
              },
}
```

There is no sort by option

**Comment by PaulL1** [comment]
OK, you can't sort the groups, that's not a current function that's available because of the way grouping uses sorting to group.  There's an open request already to add this, which includes some information about how this could be added in a PR - treeView has this capability already, grouping doesn't.

**Comment by arnoldsimha** [comment]
Thank you
