### ISSUE TITLE
bug(i18n): Header Text does not change after grid is rendered.

### ISSUE THREAD

**Issue by hk-skit** [angular-ui/ui-grid#4085]
I am using ui-grid in my project. I am implementing i18n. I have found that header text does not change once the grid rendered. I am using several local languages like English, German, Spanish. When I change from English to German or any other language, the header doesn't. I have to refresh the page to make it working. Is there any workaround for this? I have found you guys have a TODO note for it. Please let me know if there's any workaround for that.

**Comment by Olithom** [comment]
I'have the same problem. Is there any workaround today ? Render again with $rootScope.on('$uiI18n') ?

**Comment by mportuga** [comment]
I have noticed that this issue is even reproducible in the tutorial for i18n. We would welcome a PR for it.

**Comment by RajashekarReddyAleti** [comment]
I have a dropdown of languages.On selecting one language, I want to change the language of Ui-grid menu,pagination,etc.But it is not happening.
I observed that setting ui-i18n="en" in template defination in ui-grid.js file.Because of this if i set ui-i18n="some language" ,it rendering as ui-i18n="some language  en" and this causing parsing error.

Presently in my project,I included ui-grid in ng-if and setting ui-i18n="rootScope.langKey",and removed ui-i18n="en" from template in ui-grid.js file.Now ui-grid is rendering in different languages.

Please tell me is there any other solution to change language of ui-grid dynamically without modifyng ui-grid.js file.
