### ISSUE TITLE
Whats the equivalent for ng-grid's beforeSelectionChange in ui-grid?

### ISSUE THREAD

**Issue by germanger** [angular-ui/ui-grid#4207]
In this section of the documentation:
http://ui-grid.info/docs/#/api/ui.grid.selection.api:PublicApi

I see two events:

`rowSelectionChanges` and `rowSelectionChangedBatch`

What is the equivalent for `beforeSelectionChange` that was available back in ng-grid?

Why I need it and why I was using it in ng-grid?:
When the user selects a row, an ajax call is performed. While this ajax call is happenning, I don't want to allow the selection to be modified, so I used to do this:

        beforeSelectionChange: function () {
            return !($scope.doingAjaxCall);
        },

which locks selection if ajax is happenning

**Comment by germanger** [comment]
:(

**Comment by imbalind** [comment]
Question answered on Stack Overflow, I'm closing this.

**Comment by germanger** [comment]
The answer there doesn't satisfy the problem.

In fact, the answer starts with: "`This is a bit of a hack, but it'll get the job done until you find a better solution.`"

You shouldnt close this question.

**Comment by germanger** [comment]
For other users: I recommend ag-grid, an alternative for ng-grid and ui-grid

**Comment by PaulL1** [comment]
It's closed because the issues tracker is for defects with the application, not for questions on  how to use the application.  The support team are all doing this in their spare time, and need to focus on genuine defects.  Stack Overflow is the appropriate place for "how do I" type questions.

I've added some other options on Stack Overflow.

**Comment by germanger** [comment]
Isn't a defect that there isn't something that there was in the previous version? 

               ng-grid                                        ui-grid
           beforeSelectionChange   --->   nothing (defect)

Maybe is not a `genuine` defect though....

**Comment by PaulL1** [comment]
You may not be aware of it, but your tone is somewhat pushy in that last comment.

If we had stated that the new ui-grid was a superset of all ng-grid functionality, then yes it would be a defect if ui-grid didn't have some things that ng-grid used to.  However, we didn't state that.  ui-grid has many of the features of ng-grid and tried to keep similar interfaces where we could.  But there's no guarantee it has all the features of ng-grid.

ui-grid has a way to achieve what you are seeking to achieve, your issue was actually a question as to how to use that capability.  Stack overflow is the correct place for questions.

**Comment by germanger** [comment]
Sorry if it sounds pushy, but for me it is clearly a defect that `ui-grid` doesn't have an easy way of disabling selection while an ajax call is happenning. `ng-grid` had an easy way for that.

defect: a shortcoming, imperfection, **or lack.**

ui-grid lacks this feature.

Regarding closing this question: maybe I should have written this question with the shape of a defect, and not as a question itself.

**Comment by eekboom** [comment]
I came across this issue because I have a very similar problem:
When a row is selected in a master table and the detail table is switched to edit mode, then the selection in the master should be frozen.

Unfortunately isRowSelectable() is no solution because it still allows you to de-select the currently selected row.

I find it very surprising that there is no way to veto selection changes.

**Comment by piller187** [comment]
I'm running into this issue as well. I have pills that when clicked filter the grid by a status flag. Then if a user groups the grid by some other column and selects the group to select items, I need it to only select the items that meet that group AND that status pill currently selected. But this selects all items no matter status. I need a way to get all the items that are about to get selected so I can compare their status to the currently selected pill status on only allow the ones that match the pill status to be selected while not selecting the others.
