### ISSUE TITLE
Define Clear Mission Statement

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/ui-grid#4231]
Every good project needs a clear mission statement. It will help give future devs direction and help limit the scope of UI-Grid in the future. As sometimes many people have many different ideas about what a project should be I propose that we discuss and come up with a clear mission statement for the project.

Why its important: https://books.google.com/books?id=j1r4_LMo9cIC&lpg=PA36&ots=2VGrDjxco3&dq=team%20geek%20mission%20statement&pg=PA35#v=onepage&q&f=false

**Comment by JLLeitschuh** [comment]
@PaulL1 Proposed: "Most flexible and tailorable angular grid, working with native angular constructs. Free and open source. Aiming to be the default grid for any angular UI project."

**Comment by JLLeitschuh** [comment]
@swalters @c0bra @AgDude

**Comment by AgDude** [comment]
I agree it is important, and worth pursuing. Thanks @JLLeitschuh  for taking the lead on it.

I haven't given a lot of thought to it since I first saw you start this discussion, but here are a few quick thoughts on what I see as the key features of the project. I would stay away from blanket statements like Paul's (maybe joking ) comment "Aiming to be the default grid for any angular UI project."

* Handles large data sets well
* Native angular constructs
* Extendable and feature rich
* Good test coverage
* Free and open source
* Encourage and support community involvement (more than one developer behind it)

**Comment by JLLeitschuh** [comment]
Open collective needs a mission statement: Something that starts with "We are on a mission to".

How about something like:
"We are on a mission to create a flexible and tailorable angular grid that works with native angular constructs, handles large data sets well, provides a stable API, is well tested, and is extendable and feature rich. We encourage and support community involvement."
