### ISSUE TITLE
ui-grid pdf export node-webkit

### ISSUE THREAD

**Issue by jmorrisIII** [angular-ui/ui-grid#4236]
I am trying to export my grid to  PDF using a NW application. I don't get any errors but all I get is a blank window opened. Any Ideas?

```
vm.export = function(){
         $scope.gridApi.exporter.pdfExport( uiGridExporterConstants.ALL, uiGridExporterConstants.ALL );
  };
```

![image](https://cloud.githubusercontent.com/assets/7073531/9388833/8c961b2a-472d-11e5-91d9-9abc5e4e7a16.png)

**Comment by PaulL1** [comment]
Take a look at #4230.  Looks like you're on IE, export in IE is not well tested as I don't have IE to test on.  I had thought it was working to PDF, but it relied on some custom IE code that I found on the web, and has different reports as to whether it's working or not.

**Comment by c0bra** [comment]
@PaulL1 it's not IE. node-webkit uses embedded Chromium.

@jmorrisIII do you get any errors in your developer console?  I would also look at the node-webkit issues list for serving files from NW apps.

This would actually be a good candidate for a custom exporter that uses the file dialog.

**Comment by jmorrisIII** [comment]
@PaulL1 no errors in the console.

**Comment by PaulL1** [comment]
Ah, didn't look close enough - probably got fooled by the window that looked microsofty.  Could be because you're on windows.  :-)

Often the breakage will be in pdfMake itself.  I'd put a breakpoint in the code at or about the point it calls pdfMake to generate the document, check that it actually hits that line, and check the contents of the documentDefinition right before it goes in.  You can feed that same documentDefinition into the pdfMake sandpit on their website, and see if it makes a legitimate document.  Then you're left with some window handling crazy that's baked into pdfMake, and tries to successfully open a new window with a pdf in it for each of the different browser types.  Maybe try other browsers, try the tutorial pages and a few other things to see if you can rule anything in or out.

**Comment by AgDude** [comment]
I am closing this as this appears to be a problem in the underlying pdfMake library. node-webkit is also not one of our officially supported browser, although in general I see no reason it wouldn't work well with most of the grid functionality.
