### ISSUE TITLE
Resizing columns when double-clicking on column resizer in IE

### ISSUE THREAD

**Issue by romojt** [angular-ui/ui-grid#4271]
When double clicking on the column resizer in IE 10 and IE 11 the column does not resize correctly. After double clicking the column width becomes smaller than the width of the widest content.

To reproduce try to resize the name column in this example:
http://ui-grid.info/docs/#/tutorial/401_AllFeatures

**Comment by c0bra** [comment]
IE's decision making on when to ellipsize content operates differently from other browsers. I don't know if the details are documented anywhere though.

**Comment by JediMindtrick** [comment]
I just went to this same example linked above, in chrome ( Version 46.0.2490.80 (64-bit) ), typed in "Charlemagne" into the name...double-click...and the column resizes to a smaller width than the name (thereby making it unreadable).  I came here looking for answers because a team-mate of mine was having this exact problem today.

Is the example out of date, or is there some setting I missed?

**Comment by JediMindtrick** [comment]
My colleague was able to fix this problem in our case.  Our cells are using a custom template as well, which seemed to be part of the difficulty.  Not sure if it relates to IE or not as well, but here's what he found:

When using custom cell templates, be sure to add class=”ui-grid-cell-contents” to the outer element of your template (probably a div). A sample template looks like this:
``` 
<div class="ui-grid-cell-contents text-right">{{COL_FIELD}}</div>
 ```
 I had to override a couple of default styles to make the display work properly. Otherwise, it made the column a little too small and displayed an ellipse.
 
```
.ui-grid-invisible {
    display: none;
}
 
.ui-grid-cell-contents {
    overflow: visible;
}
```

**Comment by VipRepo** [comment]
Is there any fix for this? I am also facing same problem. I tried work around suggested by @JediMindtrick, but still largest column is still truncating a little.
