### ISSUE TITLE
How to use raiseSelectionEvent ?

### ISSUE THREAD

**Issue by germanger** [angular-ui/ui-grid#4283]
Can someone give me an example of how to use the method `raiseSelectionEvent` and `decideRaiseSelectionEvent`?

I want to replicate the old ng-grid `beforeSelectionChange` and Im pretty sure I need to use one of these two, but... how? The docs are not clear enough

**Comment by germanger** [comment]
Is seriously nobody using this feature? I can't imagine grid selection without it. Im still using ng-grid because of this

**Comment by germanger** [comment]
Why did you close this issue? @mportuga

**Comment by mportuga** [comment]
Because this is a question, not an issue or a feature request and per our requirements this should not be logged as an issue if it is a question. Please use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions. The UI-Grid team is now significantly smaller than it was at the time this was logged and we won't be able to ever make it through answering every single question that is ever asked here.
