### ISSUE TITLE
Dynamically added rows are not programmatically selectable 

### ISSUE THREAD

**Issue by yashgt** [angular-ui/ui-grid#4329]
http://plnkr.co/edit/4jduvwFbo5GVoWqsKwsd?p=preview

When I click the Add data button, the row gets added to the grid. I have also added code to programmatically select the newly added row. However, the rowSelectionChanged event does not get called, leading me to think that row selection does not work.

I traced the issue to Grid.prototype.getRow. The self.rows does not seem to contain the newly added row and hence this function cannot find it.

**Comment by mosheshp2** [comment]
Hi, 
as far as I understand, this is not a bug, you just need to add $timeout, so the new row will be added to the grid, and then you can select it, 
I fixed your plunkr, see row 27 in the app.js
http://plnkr.co/edit/SgL3yDWSuHIiEInRYij2?p=preview

**Comment by yashgt** [comment]
Thanks. It works.

**Comment by nkoterba** [comment]
Although this issue is closed, check out: #2267

It seems like you might just be able to call modifyData and be good.

However, in that issue report, it shows passing the grid data to the modifyData call.

However, the API documentation says `modifyData` is parameterless.

However, looking at the actual source it does appear to take data: https://github.com/angular-ui/ui-grid/blob/79e7cf2/src/js/core/factories/Grid.js#L1092
