### ISSUE TITLE
Dropdown with value and name

### ISSUE THREAD

**Issue by michelank** [angular-ui/ui-grid#4402]
Hi guys,

I'd like to use a column with a dropdown, but the example I saw it's a little confuse, I have this:
```
columnDefs: [
                    {
                        name: 'gender', displayName: 'Gender', editableCellTemplate: 'ui-grid/dropdownEditor', width: '20%', cellFilter: 'IndicesFilter',
                        editDropdownIdLabel: 'id', editDropdownValueLabel: 'gender',
                        editDropdownOptionsArray: [
                            { id: 1, gender: 'male' },
                            { id: 2, gender: 'female' }
                        ]
                    },...]
```
Then, when I end edit I just saw the id value. I'd like to see the name. Ok, then I created a filter to display it, but, should I repeat my collection there? Isn't there another way I could do it?

My filter is something like it:
```
export class Indicesfilter {
        constructor(IndiceService: IndiceService) {
            var indices = IndiceService.readAll();

            return (input) => {
                if (!input) {
                    return '';
                } else {
                    return indices[input];
                }
            }
        }

        public static factory() {
            var filter = (IndiceService: IndiceService) => {
                return new Indicesfilter(IndiceService);
            }

            filter.$inject = ['IndiceService'];
            return filter;
        }
    }
```

**Comment by Jufik** [comment]
Hello, 

If you look close enough (showing your *object* being modified:
  -*id* isn't changes when value is selected thourgh dropDown
  -*value* takes the value of the selected *id*.

Checking the source:
```javascript
$scope.editDropdownIdLabel = $scope.col.colDef.editDropdownIdLabel ? $scope.col.colDef.editDropdownIdLabel : 'id';
$scope.editDropdownValueLabel = $scope.col.colDef.editDropdownValueLabel ? $scope.col.colDef.editDropdownValueLabel : 'value';
```
I think the issue might be more general, even for *standard* {id: --, value: --} arrays.
Checking out ```javascript
$templateCache.put('ui-grid/dropdownEditor',```
on row 26636 in, replacing 

```javascript
 ng-options=\"field[editDropdownIdLabel] as field[editDropdownValueLabel] CUSTOM_FILTERS for field in editDropdownOptionsArray\"
```
by 
```javascript
 ng-options=\"field as field[editDropdownValueLabel] CUSTOM_FILTERS for field in editDropdownOptionsArray track by field[editDropdownIdLabel]\"
```

Worked for me!

Jufik

**Comment by imbalind** [comment]
This is not an issue but a design choice since, without custom filters, what you see on the grid after edit completes is just the plain entity field value.

So, if you wanted to see your label in read-only mode we had to put that inside the entity, where you usually expect to find the id.

Of course if this is not your desired behaviour you can always use a custom template (I didn't try Jufik's one, but I think something like that could work).

I'm closing this since it's not an issue. 

In an effort to better manage this project and provide support to everyone we are directing "How-To" questions to Stack Overflow. Be sure to tag your question with [ui-grid].

Our team and other users are making a concerted effort to respond people over there.
