### ISSUE TITLE
headerCellTemplate not properly resolved when providing a URL

### ISSUE THREAD

**Issue by SoundLogic** [angular-ui/ui-grid#4514]
I've created a custom `headerCellTemplate` which is very much like the regular `headerCellTemplate`, but I wanted the column filters to display above the column titles as I need the column header text to wrap per business requirements. This all works great, but I found when I was providing a URL for the `headerCellTemplate`, my header wasn't rendering. I looked at the `gridUtil.getTemplate()` function, but this appears to be resolving the template as expected so I imagine something is somehow happening out of band (maybe a side effect of one of the features I'm using?). I was able to get around this problem by setting my `headerCellTemplate`s to a promise returned from the following helper function:

``` javascript
function getTemplatePromise(templateUrl) {
    return $http.get(angular.isFunction(templateUrl) ? (templateUrl)() : templateUrl, { cache: $templateCache }).then(function (result) { return result.data; });
}
```

here is my configuration and features I am using:

``` javascript
    //configuration
    $scope.vm.gridOptions = {
            enableGridMenu: true,
            enableFiltering: true,
            enablePaginationControls: true,
            paginationPageSizes: [25, 50, 75, 100],
            paginationPageSize: 50,
            enableSorting: true,
            data: 'vm.myData',
            onRegisterApi: function(gridApi) {
                $scope.vm.gridApi = gridApi;
            }
    }
```

``` html
        <!-- features -->
        <div ui-grid="vm.gridOptions"
             ui-grid-auto-resize
             ui-grid-resize-columns
             ui-grid-pagination>
        </div>
```

anyone have any insight into what might be causing this issue?

**Comment by SoundLogic** [comment]
quick update on this as I added more custom templates I was still running into the issue so I had to initialize the `gridOptions` after a `$q.all()` to retrieve all templates and then used an `ng-if` to ensure the grid would not be rendered until the `gridOptions` were set

**Comment by Edifear** [comment]
the problem was in promise template type condition in `getTemplate` funtion,
PR created:
https://github.com/angular-ui/ui-grid/pull/5311

**Comment by david-hanger** [comment]
Since I recently had a similar problem trying to use a URL value for **filterHeaderTemplate** (and getting empty content), I posted a [comment with a recommended fix](https://github.com/angular-ui/ui-grid/pull/5311#issuecomment-324158897) to the pull request #5311.  I thought I'd reference that comment here, in case anyone else comes across this before a better fix is applied.

The above recommended workaround is basically to wait on even defining the ui-grid until after the templates have been fetched.  My recommendation in the pull request fixes template URL values to work as expected (as they do for **cellTemplate** and some others).
