### ISSUE TITLE
Adding rowTemplate or cellClass messes with selection

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ui-grid#4617]
Adding rowTemplate or cellClass messes with selection highlight color:

http://plnkr.co/edit/iMDMTltrllsrp91BbqKL?p=preview

How can I change rowTemplate but keep selection behaviour. Just want to change font color.

**Comment by imbalind** [comment]
Selection seems to work ad expected in your plunkr. It just does not show the row as selected because of your template.

I'm closing this since it doesn't look like a bug. 

 In an effort to better manage this project and provide support to everyone we are directing "How-To" questions to Stack Overflow. 

Be sure to tag your question with [ui-grid]!

**Comment by billyaraujo** [comment]
Although, it would be useful to know what is the default rowTemplate so it can be changed adequately.
