### ISSUE TITLE
ng-class doesnt work properly in rowTemplate after vertical scroll

### ISSUE THREAD

**Issue by Jegulsky** [angular-ui/ui-grid#4637]
ng-class value doesnt change real class of row div after vertical scroll.

rowTemplate looks next way:
```javascript
rowTemplate: '<div ng-class="\'text-{{ row.entity.Type }}\'" ng-click="getExternalScopes().openMessageDetails(row)"><div ng-repeat="col in colContainer.renderedColumns" class="ui-grid-cell" ui-grid-cell></div></div>',
```
Here is screenshot of the result after scroll:
![ng-class](https://cloud.githubusercontent.com/assets/1038434/10913740/5e29f7b6-8260-11e5-82e4-90efd62ca805.jpg)

**Comment by imbalind** [comment]
I think this is due to the way you defined that ng-class.

As you can see [here](https://docs.angularjs.org/api/ng/directive/ngClass) ng-class is not designed to accept Angular expressions (those in double curly braces {{ ... }}) but a javascript expression instead.

I'm closing this since it seems not related to ui-grid.
