### ISSUE TITLE
i wanna change decimal number config

### ISSUE THREAD

**Issue by eklnc** [angular-ui/ui-grid#4646]
we use to decimal number like this: 1.000.000,25
but angular ui-grid use like: 1,000,000.25

Can i change this configuration?

**Comment by imbalind** [comment]
You can try using a custom filter. Anyhow I'm closing this since in an effort to better manage this project and provide support to everyone we are directing "How-To" questions to Stack Overflow. 
Be sure to tag your question with [ui-grid]
Our team and other users are making a concerted effort to respond people on Stack Overflow

**Comment by eklnc** [comment]
Thanks for reply. I'll try that.
