### ISSUE TITLE
"Clear all filters" on gridMenu wipes out filter conditions 

### ISSUE THREAD

**Issue by zjda** [angular-ui/ui-grid#4657]
"Clear all filters" on gridMenu wipes out filter conditions as shown in the test:

http://plnkr.co/edit/7O9OkqFHoVmzHx3OiAH2

The conditions are printed to console when typing in a filter field.  Can I remove "Clear all filters" on gridMenu (as a workaround)?

**Comment by imbalind** [comment]
I don't understand the issue here.
What would you expect "Clear all filters" to do?

**Comment by zjda** [comment]
Thank you for looking at my report.  I expect "Clear all filters" will clear all search terms for all filters while keeping their conditions intact.  Otherwise the behavior of filtering function will be changed after executing "Clear all filters".  For example, my test case in the plnkr link has 3 entries:

    $scope.data=[{id: '111', name : 'john'}, {id: '112', name : 'joe'}, {id: '211', name : 'jack'}];

and the id column is defined as 

{ field: 'id', filter: {condition: uiGridConstants.filter.ENDS_WITH}}

If I type 2 in the filter field, only the second item (id=112) is displayed.  After executing the command, however,  both the second (id =112) and third (id= 211) items are displayed when I type 2 in the filter.  It is because the condition is removed by the command, which is not expected.

**Comment by imbalind** [comment]
The problem is in [ui-grid-menu-button.js](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/js/core/directives/ui-grid-menu-button.js#L196) where we call `grid.clearAllFilters` passing `true` as the second parameter.

In [Grid.js](https://github.com/angular-ui/ui-grid/blob/e89598a588791a6fc18a040c00a805dc1b6c5d25/src/js/core/factories/Grid.js#L2467) (and in `clearAllFilters` docs) we can see that the second parameter's meaning is exactly whether to clear conditions or not.

I don't know if that behaviour is the desired logic or maybe an error, but I have to admit I see no point in clearing conditions set by the devs.

If you feel like you can propose a PR to change said behaviour and the team will decide whether to accept it or not.

Sadly I think there is no way to remove that specific menu button when filtering is enabled.

**Comment by zjda** [comment]
It will be appreciated if you can tell me where I can submit the PR?  Thanks,

**Comment by imbalind** [comment]
You can start reading the files:

- FIRST_TIMER.md
- CONTRIBUTING.md
- DEVELOPER.md

You can find them at the root folder of source code.

**Comment by zjda** [comment]
I will read the documents and submit the PR.  Thank you very much.

**Comment by lebolo** [comment]
I've created PR #5361, and all tests pass, but still not sure why the original source cleared `conditions` or what the intention was.

**Comment by ravivantaku** [comment]
Hi,
I need to call a function when i click on "clear all filters"  in grid menu, because i need to clear custom filters also when i click on "clear all filters".  Can any one help me? how  to handle the grid menu clear all filters click event.
Thanks in advance.
