### ISSUE TITLE
Angular ui grid refresh

### ISSUE THREAD

**Issue by Priya9136** [angular-ui/ui-grid#4695]
I want to refresh the ui grid through $http get call with new data.The call is made when a user changes the date in the datepicker and I trigger the $http on a ng-change event.The call is successfull but the grid does not update with new data. It retains the old data. Can you suggest ways to refresh the grid dynamically with new data.

**Comment by imbalind** [comment]
Hi thanks for your inquiry.

In an effort to better manage this project and provide support to everyone we are directing "How-To" questions to Stack Overflow.

Our team and other users are making a concerted effort to respond people on SO.

Be sure to tag your question with [angular-ui-grid]!

**Comment by PaulL1** [comment]
Usually this is because you are not using gridoptions.data = 'data', but rather doing gridoptions.data = $scope.data. The latter won't update when you overwrite $scope.data.

Sent from my iPhone

On 14 Nov 2015, at 4:19 PM, Priya9136 <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to refresh the ui grid through $http get call with new data.The call is made when a user changes the date in the datepicker and I trigger the $http on a ng-change event.The call is successfull but the grid does not update with new data. It retains the old data. Can you suggest ways to refresh the grid dynamically with new data.
