### ISSUE TITLE
UI grid not refreshing data when updated

### ISSUE THREAD

**Issue by vignesh9136** [angular-ui/ui-grid#4696]
-1

down vote

favorite

I am calling $http.get to get new content from the server for angular ui grid. On change of date in the datepicker I trigger an ng-change event to make another http call to get new content. The call is successful but the grid is not updated with new content.$scope.grid.core.notifyDataChange() throws error when called inside the http success call back.Please suggest ways to update the grid with new content.

Please find the plnkr code. when I click load button, I want to update grid with new JSON data using http call but it is not updating grid. http://plnkr.co/edit/S2A3scEoO6QIGFbru3Lr?p=preview

**Comment by alexhuang92** [comment]
try calling $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL)

**Comment by geovizcoder** [comment]
Me facing a similar issue. 

$scope.myData= filteredData; // new dataset
$scope.gridOptions.data = $scope.myData;

$scope.myData has the new data. console.log confirms it, But when the grid updates, it displays the right number of rows though, but just repeats/duplicates the last row of the original data set -not the new dataset-as many times as the new count. Clicking on any row then selects all the rows and the footer implies only one row is selected.

**Comment by PaulL1** [comment]
The plunker has a lot of stuff that doesn't appear essential to your example - stuff to do with the expandable grid.  I could take all that out to get down to a test case that does just what it needs and no more, but then I'd not know whether I still had something that reflected your problem.

Any chance of making a smaller plunker that has only the essential elements of the problem?

My best guess, absent that review, is that it's in the way you're handling the `$scope.gridOptions.data`.  The normal usage I've seen is:

```
$scope.myData = roData;
$scope.gridOptions.data = 'myData';
.....
  some time later in the code
.....
$scope.myData = rData;
```

This tends to be more reliable, otherwise I've seen people getting object references pointing where they don't expect.
