### ISSUE TITLE
gridOptions.data doesn't work

### ISSUE THREAD

**Issue by paulserikov** [angular-ui/ui-grid#4697]
This code is working:

```html
<head>
<script type="text/javascript">
	(function(){
		var app = angular.module('main', ['ngResource', 'ui.grid', 'ui.grid.edit'] );
		app.factory("Items", function($resource) {
	  		return $resource("/api/items/:id");
		});
		app.controller('ItemsController', function($scope, Items) {
			$scope.gridOptions={
				columnDefs : [
					{ name: 'id', enableCellEdit: false, width: '20%' },
					{ name: 'Item name', enableCellEdit: true, width: '80%' },
				],
				data : Items.query()
			};
			$scope.msg = {};
			$scope.items = Items.query();
		});
	})();
	</script>
 </head>
 <body>
  <div class="container" ng-app="main">
 		<div ng-controller="ItemsController">
		 	<div ui-grid="{ data: items }" ui-grid-edit></div>
		</div>
    </div>
</body>
```

And this code no:

```html
<head>
<script type="text/javascript">
	(function(){
		var app = angular.module('main', ['ngResource', 'ui.grid', 'ui.grid.edit'] );
		app.factory("Items", function($resource) {
	  		return $resource("/api/items/:id");
		});
		app.controller('ItemsController', function($scope, Items) {
			$scope.gridOptions={
				columnDefs : [
					{ name: 'id', enableCellEdit: false, width: '20%' },
					{ name: 'Item name', enableCellEdit: true, width: '80%' },
				],
				data : Items.query()
			};
			$scope.msg = {};
			$scope.items = Items.query();
		});
	})();
	</script>
 </head>
 <body>
  <div class="container" ng-app="main">
 		<div ng-controller="ItemsController">
		 	<div ui-grid="gridOptions" ui-grid-edit></div>
		</div>
    </div>
</body>
```

Is there any problems with **gridOptions.data** in latest version?

I'm using  ui-grid - v3.0.7 - 2015-10-06

**Comment by geovizcoder** [comment]
Me facing the same issue.

**Comment by PaulL1** [comment]
Can you provide some information about what's different between those two code samples - it's not immediately obvious (they look quite similar).

Any chance of providing a plunker and explaining exactly what the problem is that you have?

Usually for problems with gridOptions.data I'd recommend using the alternative format, as it seems to avoid people getting javascript pointer issues:

```
  $scope.items = Items.query();
  $scope.gridOptions.data = 'items';
```

**Comment by PaulL1** [comment]
The issue doesn't look to have anything to do with your definition, it's because your column defs aren't giving field names from your object array.

You should use `displayName` for the title you want in the grid, and `name` for the actual object name in your data array.  Like so: http://plnkr.co/edit/BGq3zdck4b49nByU4H69?p=preview

**Comment by paulserikov** [comment]
Thank you very much.
I just begin with UI Grid so did't know that details so any help is much appreciated
Please also check my another report https://github.com/angular-ui/ui-grid/issues/4750 I got stuck in this place too.
