### ISSUE TITLE
Get Filtered data from paged ui-grid

### ISSUE THREAD

**Issue by darksonwolf** [angular-ui/ui-grid#4718]
I'd like to get filtered data from a ui-grid when the paging feature is enabled. In general case I used `getVisibleRows` but it doesn't work well when the paging is enabled, it return only rows of the first page. but I need all the filtered data.

the easiest solution is filter data source based on the filter term but it decreases the performance dramatically.

**Comment by greggriffin** [comment]
Can you provide me an example of how you are re-filtering the data in code?

**Comment by crazyjat** [comment]
I desperately need this capability as well. How is there no built in way to get the filtered data set?

**Comment by PaulL1** [comment]
There is a way to get the filtered data set.  The only problem is that pagination counts as filtering.  Some people would want that, other people have use cases where they want the filtered data but not the paged data.

**Comment by crazyjat** [comment]
What way is that? 

The only way I have seen to even get close to filtered data is getVisibleRows. But as the name implies, that would only return the VISIBLE rows, regardless of pagination. Since ui-grid uses a dom recycling method to reduce the number of dom elements created for rows (unless I read that wrong in the documentation), doesn't that imply that getVisibleRows will only return what is literally visible within the grid view? The documentation doesn't specify anything useful about getVisibleRows.
