### ISSUE TITLE
scrollTo doesn't work with higher rowHeight

### ISSUE THREAD

**Issue by projectX21** [angular-ui/ui-grid#4776]
Hello everyone,

I've found a little Bug:
If you use a custom rowHeight, the scrollTo will not scroll exactly to the specified row.

I have a little example:
http://plnkr.co/edit/bO4JGSCeraASMTZ04zhA?p=preview

When you scroll down, and click the button "Go to top" afterwards, it will not scroll exactly to the first row.

Do you have a workaround for that problem? This is needed in my project.

Thank you for your help!

**Comment by yehuabin** [comment]
Can  $http.get support cross domain?

**Comment by projectX21** [comment]
Sorry but I don't get it. Is that related to my question?

**Comment by yehuabin** [comment]
sorry not related. that just my a question

**Comment by imbalind** [comment]
@projectX21 the problem is [here](https://github.com/angular-ui/ui-grid/blame/f71576756e9b91ded1b01f2a9f740c1a79d18c60/src/js/core/factories/Grid.js#L2335) where you can see:

    var pixelsToSeeRow = ((seekRowIndex + 1) * self.options.rowHeight);

here the `+1` is needed to account for the header, but this is obviously right only if `rowHeight === headerHeight`. To make it more generic this should come:

    var pixelsToSeeRow = ((seekRowIndex) * self.options.rowHeight + self.headerHeight);

**Comment by projectX21** [comment]
Thank you very much for this hint!

But is there a possibilty to get this work without modifing the source code?

**Comment by imbalind** [comment]
Meh.. I don't think so. Unless you can afford to have headers as high as the rows are.

**Comment by imbalind** [comment]
[Here](http://plnkr.co/edit/AZoYdm1XKJDG84z20ogF?p=preview)'s a modified version of the plunkr, I had to add a minified version of ui-grid.js because of size issues.

**Comment by kylehoehns** [comment]
@JLLeitschuh any idea when the ```3.0.8``` release is scheduled? We are running into this same issue after upgrading from ```3.0.1``` to ```3.0.7``` and were hoping we could get this fix before our next release.

**Comment by projectX21** [comment]
But ist there an option to define the height of the header? On the wiki page I don't find such a property.

**Comment by lvostinar** [comment]
This issue is still not fixed. See http://plnkr.co/edit/aIxHXHKTSlxeSDavfqtR?p=preview . When pressing Scroll to top it scrolls to row with id 498. Scrolling is not really correct, row is only partially visible (with header height). So, now, scrolling as first row works well but scrolling as last row is broken. 

See also comments from https://github.com/angular-ui/ui-grid/issues/4204 , which is a duplicate issue.
