### ISSUE TITLE
cellnav on.navigate called on scroll

### ISSUE THREAD

**Issue by lvostinar** [angular-ui/ui-grid#4835]
see http://plnkr.co/edit/eIO6BGBNlO5szhwqqqar?p=preview , if cellnav is enabled and I select a cell in grid, then on.navigate is called at each scroll with same value (see browser console in plnkr); this is a regression from https://github.com/angular-ui/ui-grid/issues/3815 , now on scrollstart the focused cells are cleared

this is quite big issue for us, we are using it in more complex scenario where we scroll the grid while other input field is focused, this bug causes the grid to request focus back

**Comment by imbalind** [comment]
The problem is [this line](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/features/cellnav/js/cellnav.js#L684) where `grid.api.cellNav.raise.navigate(newRowCol, grid.cellNav.lastRowCol)` gets called when scroll ends.

This is due to the following stack:

- `grid.api.core.on.scrollEnd` [`cellnav.js#L992`](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/features/cellnav/js/cellnav.js#L992)
- `cellNav.broadcastCellNav` [`cellnav.js#L662`](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/features/cellnav/js/cellnav.js#L662)
- `cellNav.broadcastFocus` [`cellnav.js#L684`](https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/src/features/cellnav/js/cellnav.js#L684)

I think we should put a check at some point and stop this flow if `newRowCol === grid.cellNav.lastRowCol` but I'm not as confident in when this is called (other then when scrolling, I think it gets called when using arrow keys, tab, return, ecc.).

@lvostinar do you think you could try putting that check in one of those places and check if anything still works? If you could make a PR and verify nothing breaks I'll merge it.

**Comment by lvostinar** [comment]
Ok, here it is: https://github.com/angular-ui/ui-grid/pull/4874
