### ISSUE TITLE
Unable to open dropdowns when i upgrade ui-grid-v3.0.0-rc.21-aa56355  to ui-grid-3.0.7

### ISSUE THREAD

**Issue by ravivantaku** [angular-ui/ui-grid#4838]
I have an issue when i was upgrade ui-grid-v3.0.0-rc.21-aa56355  to ui-grid-3.0.7. 
The issue is, i am displaying  some data in drop downs by using cellTemplate, but these are not opened.
I found one reason to cause this issue that is,  When i remove ui-grid-cellNav  from ui-grid attributes then these drop downs are working but cell selection and row selections are not working. I need these dropdowns and selection for my requirement . I created a plunker to produce this issue for better understand.  http://plnkr.co/edit/0m0AKrQ9ppDN4MsW3bIA?p=preview  . Please suggest a solution for this issue.
Thanks in advance.

**Comment by imbalind** [comment]
The issue is related to the way we manage clicks in ui-grid-cellNav to provide selection. In order to do this we prevent the usual click events to propagate, thus your dropdown is not opening.

The way you are using an editable content without using ui-grid-edit is not the usual way so we won't accept this as a bug.

I'd suggest you go for the proper editing way, if it's compatible with your requirements, otherwise you could try to ask for further help on a Q&A website like stack overflow.

Our team and other users are making a concerted effort to respond people on SO.

Be sure to tag your question with [angular-ui-grid]!

**Comment by ravivantaku** [comment]
Thanks  @imbalind for quick response.
Even i added ui-grid-edit directive to ui-grid div then also it doesn't work. 
Actually my grid has contains 30 plus columns and every column must have cellTemplate, in those columns  some columns are dropdowns and some are input text boxes. I have used all the ui-grid features i.e ui-grid-edit, ui-grid-selection, ui-grid-pinning, ui-grid-save-state, ui-grid-cellNav, ui-grid-grouping etc. It works perfectly with ui-grid-v3.0.0-rc.21-aa56355 but it doesn't work with ui-grid-3.0.7. The updated plunker is given http://plnkr.co/edit/0m0AKrQ9ppDN4MsW3bIA?p=preview
