### ISSUE TITLE
Columns lose 1 pixel of width, causing alignment drift in Firefox

### ISSUE THREAD

**Issue by JavaJesus** [angular-ui/ui-grid#4845]
I'm running into a problem where on Firefox my columns will lose a single pixel compared to the headers which adds up over time. I have a barebones example set up on my personal website  (http://www.njriccio.com/uigridtest.cfm) because frustratingly the alignment drift doesn't occur in my Plunkr test: http://plnkr.co/edit/oufUq29PnMrEZLFpfbYL?p=preview

I've tested using 3.0.1, 3.0.7, and the files given to me by the npm install and the drift persists through all of them, and I had a coworker pull up the example on my website where he saw the drift which rules out a weird Firefox setting.

**Comment by imbalind** [comment]
I can confirm your problem, on your website page, but since it seems not reproducible in a controlled enviromnent as plunker is, we cannot accept this as a bug.

I'd suggest you to try to get some answer on a Q&A website like stack overflow, but I'm afraid they would need a code the could reproduce too.

If you managed to get this issue in plunker feel free to open a new issue or post on stack overflow!
