### ISSUE TITLE
Need to change the code format when export to csv.

### ISSUE THREAD

**Issue by hxlniada** [angular-ui/ui-grid#4866]
When export to csv, the chinese has messy code.
I need to change the code format to ansi.

**Comment by imbalind** [comment]
This is just issue #4865 rewritten without a question mark.

If you want to file a bug, you should provide a case where the library is not working as the docs say, a plunker example would be appreciated.

If you want to propose an enhancement you should provide context and guidelines on what the library should do.

From what I understand you have a problem with encoding, while the encoding the grid support is `charset=utf-8` as you can see [here](https://github.com/angular-ui/ui-grid/blob/84829f539ba009dbfce2e398135fae8a618ecdd0/src/features/exporter/js/exporter.js#L913).

If you need to change your code format to ANSI there are a lot of way to do so and I think that a Q&A website like Stack Overflow would be your best bet. 

If you think that the grid should do so by default this would be an enhancement proposal but I don't see it's likely it would be accepted since UTF-8 is way a better standard (greater set of characters).

**Comment by hxlniada** [comment]
Look through the api. I can't find a entry to set encoding.
If the user is me, I can change the encoding manualy.
But our users are angry.

**Comment by imbalind** [comment]
What's the exact encoding you need?

**Comment by hxlniada** [comment]
Ansi

**Comment by imbalind** [comment]
ANSI is not exactly an encoding: http://stackoverflow.com/questions/701882/what-is-ansi-format could you please be more clear?

**Comment by AgDude** [comment]
Please post question to gitter or Stack Overflow. Issues should be opened for bug reports only. thanks
https://github.com/angular-ui/ui-grid/blob/master/CONTRIBUTING.md
