### ISSUE TITLE
ui-grid prevent focus on column headers while tabbing through the page

### ISSUE THREAD

**Issue by nawanshu** [angular-ui/ui-grid#4951]
I have multiple controls on the page, one of them is ui-grid. When user is tabbing through the page., focus goes to grid header before going to the first row. However, that is not what I want. I want the focus to directly jump to the first selected row.

I found one workaround for this by modifying 'ui-grid/uiGridHeaderCell' template in ui-grid.js to have tabindex="-1". However I am looking for a cleaner method for this.

**Comment by pjwalmsley** [comment]
+1 

A cleaner solution would be to remove the tab-index="0" property.  

We should also allow for sorting and filtering using the keyboard if those filters are enabled.  When tab index is removed from the header label focus goes directly to the filters as intended.  However there is no way to sort.  Tabbing bypasses the column (sort) menu when it's present.  When it's not present a user can typically toggle the order by clicking the header with their mouse.  That may be a reason to place focus on the header.  However if we choose to place focus there we should enable the user to toggle the sort order using their keyboard.  

It's worth noting that keyboard navigation is generally poorly implemented.  

Tabbing through the headers skips the Grid menu (far right) despite not skipping column menus (used to sort).  

There is also another bug on record for tabbing through rows.  It suggests that when cells are not editable rows should be highlighted rather than cells which would make navigation and row selection easier.  

For a temporary fix I plan on disabling any keyboard navigation on the grid or replacing the header cells with my own.

**Comment by stl1975** [comment]
For the keyboard navigation issue where the focus goes to the grid header before going to the first row, could you please let us the priority of this bug in UI-Grid queue list.
This is one of the important feature required by our business users, so we would like to know if this bug would be fixed in the coming release of UI-Grid. 
We would love to lend a hand by fixing it with your guidance, let us know!

**Comment by swalters** [comment]
@stl1975 we'd love some help with this issue. 

How best to implement?   

What if the header could not get focus by tabbing.

 Clicking on something in the header set focus to it.  Then the user could tab anywhere in the header.  

Once the grid body has focus again, then the header can't get focus without an explicit focus.

**Comment by stl1975** [comment]
@swalters , the behavior you described 29 days ago is exactly the behavior we desire.
Do you need assistance in making this happen, where we would alpha test the feature?
Please reach out if you would like us to participate right away.

**Comment by cortezcristian** [comment]
In the middle time you can use this simple directive:

```
.directive("uiGridHeaderCell", function(){
      return {
        restrict: 'C',
        link: function(scope, element, attrs){
          element.find('[role="button"]').removeAttr('tabindex');
        }
      };
  })
```

Best,

**Comment by anuradha18** [comment]
How to use the uiGridHeaderCell directive. Is it on the column level using an cellTemplate

**Comment by anuradha18** [comment]
I added the directive class after registering the grid. It is removing the tab index but still navigating

**Comment by stan-z** [comment]
```js
angular.module('ui.grid').run(['$templateCache', $templateCache => {
    // Remove header tabindex
    const headerCellTemplate = $templateCache.get('ui-grid/uiGridHeaderCell');
    if (headerCellTemplate) {
        $templateCache.put('ui-grid/uiGridHeaderCell',
            headerCellTemplate.replace(/\stabindex="0"/g, '')
        );
    }
}]);
```

**Comment by fatifleu** [comment]
@stan-z  can you explain to me where to put this code

**Comment by stan-z** [comment]
After `ui-grid` angular module is included. It removes `tabindex` from the default [ui-grid/uiGridHeaderCell](https://github.com/angular-ui/ui-grid/blob/master/src/templates/ui-grid/uiGridHeaderCell.html) template. You can also define the custom  `columnDef` [headerCellTemplate](http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef#properties_headercelltemplate).
