### ISSUE TITLE
Change Style of Treeview column ( the +/- expand/collapse)

### ISSUE THREAD

**Issue by benjaminmbrown** [angular-ui/ui-grid#5001]
how can one change the +/- icons and background programmatically to different icons?

**Comment by yccteam** [comment]
Change the icon:
Check this css definition -
`.ui-grid-icon-plus-squared:before`. It has a `content` property. Override it for a different icon.
In order to change background - 
`.ui-grid-tree-header-row` 
might do the trick for you.
Another way would be to get the template and use it (watch for the `treeBase` templates).
