### ISSUE TITLE
ng-click from a cell template does not work

### ISSUE THREAD

**Issue by aseemflowingly** [angular-ui/ui-grid#5002]
I am trying to add actions for a row in the last column.

I have modified the cell template to specify a function on the angular controller to be called from "ng-click" for a button. But it does not work.

Plnkr : http://plnkr.co/edit/z48bTEBqtejA3JfJiPc4

What am I doing wrong?

**Comment by B8li** [comment]
Hi @aseemflowingly,

Here is working plnkr : http://plnkr.co/edit/j6EYoyej9sgyrAaUSiSa
Note how to call your function from the current scope: `ng-click="grid.appScope.doSomething($index)"`. 
This is specified in the tutorial : http://ui-grid.info/docs/#/tutorial/317_custom_templates

Hope that this helped, if so please close this issue and in the future please create questions on Stack overflow with tag `angular-ui-grid` instead of creating issues on GitHub.

Best regards,
Igor

**Comment by aseemflowingly** [comment]
Great thanks! @B8li
