### ISSUE TITLE
Grid infinite-scroll calls infinitely `needLoadMoreData()`

### ISSUE THREAD

**Issue by DerekDomino** [angular-ui/ui-grid#5022]
When the end of the data stack is reached (i.e., when `needLoadMoreData()` returns no more data), Grid calls `needLoadMoreData()` an incredible amount of times.

Commit [65a541f3](http://github.com/angular-ui/ng-grid/commit/65a541f39c708a070244e09aa0c7bbe4b0506eff) should check about the previous call result. If the previous result is empty then data retrieval should not be triggered.

**Comment by PaulL1** [comment]
I think in the tutorial the service that returns more data sets "moreDataBottom" to false if no more data is available, which then stops this event from firing.  I think that's the correct approach rather than the grid attempting to deduce whether getting a nil response once means we'll get a nil response forever.
