### ISSUE TITLE
Editable cell input height

### ISSUE THREAD

**Issue by geraldpereira** [angular-ui/ui-grid#5047]
Is there a way to change the height on the input text that appears when a cell is edited (via ui-grid-edit)?

I tried to inspect the input using Chrome dev tools, but it disappears when the page loses focus.

**Comment by imbalind** [comment]
You should do it via CSS as you were trying. To avoid it disappearing I suggest using [Javascript Pause Keyboard Shortcut](https://chrome.google.com/webstore/detail/javascript-pause-keyboard/djloabcambmaldcfnacbemhefnbfafom?hl=en).

With that you could pause the execution of the code and inspect any web page as it is in any given moment.

I'm closing this since it's not a bug, if you have further question, you should post them on a Q&A website like Stack Overflow! Thanks!
