### ISSUE TITLE
how to add new row in between rows in angular UI Grid

### ISSUE THREAD

**Issue by Shreeshag** [angular-ui/ui-grid#5053]
Hi,

I am new to the angular UI-Grid,

Can any one help me, how to insert new row in-between selected row in UI-Grid.

**Comment by PaulL1** [comment]
In order to change the rows you just need to change your data.  To insert a row I think you use splice on an array.  Check the tutorials, there are some that manipulate the data.  

Questions of this nature should really go on stackoverflow, rather than into the issues tracker - this isn't an issue.
