### ISSUE TITLE
Bower/npm install doesn't download DevDependencies for export to PDF/CSV

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [angular-ui/ui-grid#5172]
I wanted to ask if is there any problem in the packages files, because a few days ago I installed ui-grid via bower and i wanted to use pdfmake, csv and vfsfonts and had to download it by hand. It isn't supposed to be on the package when installed via bower or npm?

**Comment by manijak** [comment]
@tiagomsmagalhaes: 
I was wondering the same thing. These libraries are not part of angular or ui-grid, so you need to add them seperatly. So in your bower.js add the following and it will download the files you need: 
```json
"pdfmake": "0.1.20",
"csv-js": "1.1.1"
```
 I found that these are equal to those that ui-grid uses in its export-example.

**Comment by mportuga** [comment]
Well, the documentation on export data does specifically calls out that you need to download pdfmake in order to use that feature.

http://ui-grid.info/docs/#/tutorial/206_exporting_data

Also, my understanding is that since not everyone uses these features, we didn't want to call them out as dependencies. The only thing you really need to use ui-grid is angular.
