### ISSUE TITLE
Where do we ask questions if we want to help contribute to the code?

### ISSUE THREAD

**Issue by rmechamatadobe** [angular-ui/ui-grid#5217]
Where do we ask questions if we want to help contribute to the code?

I'm trying to modify the code and debug it with IntelliJ running locally but the interface hosted by the local URL:
http://localhost:9003/#

includes the minified js code from the url:
//ui-grid.info/release/ui-grid-unstable.min.js

I've tried changing the index.html file to use the local file either by direct file:/// protocol or by using the local web server but none of these attempts worked.
I.E. <script src="file:////Users/rmecham/dev/ui-grid/ui-grid/dist/release/ui-grid.js"></script>

Is there a build configuration that runs the test site from the local ui-grid code?

I apologize in advance if this question has already been answered somewhere and I've missed it.

Any help would be appreciated.
rmecham@adobe.com

**Comment by mportuga** [comment]
When developing code with grunt dev. I suggest going against the tutorial pages over the home page. Perhaps, we need to add a chore to make it so that the home page is also useful for devs. But going against any of the tutorial pages works well in my experience. And the grunt dev task creates a watch that automatically minifies the code you are writing as you make changes. I suggesting reading the following pages:

https://github.com/angular-ui/ui-grid/blob/master/DEVELOPER.md
https://github.com/angular-ui/ui-grid/blob/master/CONTRIBUTING.md
