### ISSUE TITLE
How one grid filter another.

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ui-grid#5328]
Hi,

I have two grids with two controller.

How make a custom filter to, if select one row of first grid make filter on the second grid.

Thanks.

**Comment by stevenlius** [comment]
Questions like this should posted on Stackoverflow as it is not a issue related to the ui-grid. 

To your question: 
OnRegisterApi, you should register the filter changed, as following for external sort
```
gridApi.core.on.filterChanged($scope, function() {
                    $scope.getFilterChanged(gridApi.grid);
                });
``` 
This will give you live update of what user have put in all input fields. 

Then in order to update second grid, you need to have a listener on the grid div tag, as ng-pressed to trigger function call. 

Then you can update the second grid however you want.

**Comment by lecoleco** [comment]
thank you
