### ISSUE TITLE
ui-grid.info down

### ISSUE THREAD

**Issue by prettycode** [angular-ui/ui-grid#5412]
Since yesterday:

![image](https://cloud.githubusercontent.com/assets/396873/15360508/abc78ca2-1cc2-11e6-8271-67c5392c5483.png)

**Comment by laviyatziv** [comment]
Same here. Is there a repo of the docs?

**Comment by user178192** [comment]
Same problem.

**Comment by mikeytag** [comment]
I'm seeing the same thing and getting 503 on every partial request in the /docs/ app.

![screen shot 2016-05-18 at 11 25 02 am](https://cloud.githubusercontent.com/assets/219403/15370299/40f17e78-1ceb-11e6-83ce-8c2a4ee129bb.png)

**Comment by bacable** [comment]
Same here. It'd be nice to have an alternate location for the documentation/tutorials. Have a time sensitive question that looks like stack overflow alone can't help solve, but the site's been down all day for me.

**Comment by mikeytag** [comment]
Here here. I'm in the depths of SO trying to find people that copied and pasted stuff from the documentation/tutorials but coming up short.

**Comment by mikeytag** [comment]
Hey everyone! I was browsing the repo and found this: https://github.com/angular-ui/ui-grid/tree/master/misc/tutorial  It's not great but all the partials for the docs/tutorial seem to be in the misc folder of the project!

**Comment by moses-seeq** [comment]
It's back!

**Comment by c0bra** [comment]
Sorry about this everybody! The domain was originally purchased through badger.com which shut down officially yesterday. I had transferred the domain to a different registrar but neglected to alter the name servers as well.

@bacable If, God forbid, something like this happens again, since the site is hosted on github pages you can find the doc contents in this repository: https://github.com/angular-ui/ui-grid.info/tree/gh-pages/docs
