### ISSUE TITLE
http://ui-grid.info/ site is down.

### ISSUE THREAD

**Issue by ajaysingh9** [angular-ui/ui-grid#5418]
Hi There,

The Site 'http://ui-grid.info/' is down, how quickly this can be fixed?

**Comment by prettycode** [comment]
It's back up, for me. Checked over work network and home network.

**Comment by boods31** [comment]
Ticket #5412 (ui-grid.info down) was opened and closed as fixed, but it still does not work for me.
It did work once, but is down most of the time

**This site can’t be reached
ui-grid.info’s server DNS address could not be found.**

Here was the response from 5412:

**c0bra commented:**
Sorry about this everybody! The domain was originally purchased through badger.com which shut down officially yesterday. I had transferred the domain to a different registrar but neglected to alter the name servers as well.
**@bacable** If, God forbid, something like this happens again, since the site is hosted on github pages you can find the doc contents in this repository: https://github.com/angular-ui/ui-grid.info/tree/gh-pages/docs

**Comment by boods31** [comment]
Even this site: http://angular-ui.github.io/ui-grid/  has a link to

News! ng-grid has been rewritten as **UI Grid**, it's now stable! Check it out.

Clicking on the **UI Grid** link does not work for me. I also get
ui-grid.info’s server DNS address could not be found.

**Comment by boods31** [comment]
It is now back up. All appears to be working for real this time.
Hope it is working for the rest of you.

**Comment by pccjamie** [comment]
Still down.

**Comment by pccjamie** [comment]
@boods31  - That site is for 2.0.  Nothing is available for 3.0

**Comment by boods31** [comment]
Everything is working again and the site is up. 

Jim

**Comment by boods31** [comment]
It was still down and now it's up. I was just trying to show the same issue somewhere else.  Thanks for replying. 

Jim
