### ISSUE TITLE
laggy scroll with large dataset

### ISSUE THREAD

**Issue by Biraja-Github** [angular-ui/ui-grid#5423]
Hi Team,

First of all, thanks for the awesome grid.
I am using ui-grid with large dataset (75rows and 256 columns per page). Cell contains templates like links, popovers, hover effects, tables, dropdown, images etc.
With this kind of data, if i start scrolling, performance is very laggy. For some fraction of seconds, i can see white background in grid itself and also horizontal scrollbar hangs/sticks while dragging.

Request you please look into this.

Thanks,
BIRAJA

**Comment by angular-git-user** [comment]
This is because grid renders only those columns that user can see at a time on the browser.
as you start scrolling the hidden part starts rendering and the previous rendered data is now removed from the dom... this makes the column filtering and other features faster as it does not have to render entire rows..
I believe this was the best feature in UI Grid.... but if you still want to overwrite this then set 
`gridOptions.virtualizationThreshold: greater than or equal to the total number of rows`
`gridOptions.columnVirtualizationThreshold: greater than or equal to the total number of columns`

For more details you can look into the source code

**Comment by Biraja-Github** [comment]
Hi @angular-git-user ,
i have used virtualizationThreshold & columnVirtualizationThreshold. It is working fine for less number of columns(5-10) but in case of 256 columns, the grid becomes unresponsive(not able to interact with UI) for 30 to 40 secs.

Please suggest a solution.

Thanks,
BIRAJA

**Comment by angular-git-user** [comment]
Then it's not possible... since entire dom is being rendered it would slow all the process

**Comment by mportuga** [comment]
As @angular-git-user has pointed out, this is not possible. Closing this issue.
