### ISSUE TITLE
custom aggregation for ui grid

### ISSUE THREAD

**Issue by nharikakoneru** [angular-ui/ui-grid#5485]
My aggregates function would like to perform a calculation using the summary of 2 other columns that are aggregated
individually already (sum aggregate) –
for example – I have a cost column and an items column.Both have the Sum aggregates function.
I would like in the third column aggregates (summary row) to show the sum of cost divided by the sum of items.

**Comment by jniles** [comment]
The best way to do this would be with a custom footer cell in the third column.  UI Grid expects all aggregation values to be an aggregation of that field/column.  Since the aggregation you want is actually an operation on the aggregation results of two other columns, you will want to make a custom footer cell template and use [getAggregationValue()](http://ui-grid.info/docs/#!/api/ui.grid.class:GridColumn#methods_getaggregationvalue) to get the values of the other two columns and add that result together.

**Comment by smhnkmr** [comment]
Thanks @jniles, this will work fine for calculating the footer value. How can I calculate the sum for grouped rows?

**Comment by jniles** [comment]
That would have to be a custom template cell using the same principle.  You can check to see if it's a group header by checking `ni-if="row.groupHeader'` and then either rendering a calculated value or the default value which is `{{COL_FIELD CUSTOM_FILTERS}}`.

I'm not sure how you'd figure out what the correct values were at that grouping level though for the other columns, but I'm sure there is a way with some digging.  Maybe the treeBase documentation will have more?
