### ISSUE TITLE
UI-Grid not resposive

### ISSUE THREAD

**Issue by myselfjd** [angular-ui/ui-grid#5604]
Hi Team,

As the screen resolution increases , we are getting the empty column space in right side of the grid
can any one suggest , how to make UI-Grid responsive.

Thanks,
myslefJd

**Comment by angular-git-user** [comment]
that is the feature of UI Grid you must read this [http://ui-grid.info/docs/#/tutorial/316_dynamic_data_changes](dynamic_data_changes)

**Comment by angular-git-user** [comment]
if you still don't need that white spaces which blinks you can set columnVirtualizationThreshold to the number of  columns, which will render all the columns once. But this comes with a cost on performance (while filtering, sorting etc since if the number of columns are huge it takes  time to render all the columns)

**Comment by myselfjd** [comment]
@angular-git-user thanks for your reply, but i did not find any  columnVirtualizationThreshold  property in configuration of ui-grid,but found one which is depricated from the version 3.0 (enableColumnHeavyVirt ),currently  im using version 3.0.
