### ISSUE TITLE
UI Grid Menu Items - When Show Hide Columns from Grid Menu, the items Jumps in IE

### ISSUE THREAD

**Issue by shaileshayer** [angular-ui/ui-grid#5634]
Please make sure each of the following is true before submitting a new issue.  We are a small team with limited time and it is very difficult to manage issues if they aren't reported correctly.
- [ ] This is a bug report, not a question on how to use the grid.  
  Use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions.
- [x] You have searched the open issues to see if this bug has been filed before.  We don't want duplicate issues.
- [x] You have reviewed the tutorials and documentation to ensure you are using the grid correctly. [ui-grid.info](http://ui-grid.info/docs/#/tutorial)
- [x] You are using the latest version of the grid. Older versions are not patched or supported.
- [ ] You have provided steps to recreate your bug.  A plunkr is even better.

**Comment by shaileshayer** [comment]
Hi when i Try to do show hide of columns form Grid menu the Menu items jumps up and down in IE

**Comment by mportuga** [comment]
My theory on this is that rather than having one button that toggles column visibility, UI-Grid has 2 buttons per column one for hiding columns, and one for showing. And they which button is visible is toggled as they are clicked. Merging those duplicate buttons into 1 should resolve this issue as well as improve the overall performance of the grid.

This is where we want to make that change: https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-menu-button.js#L261
