### ISSUE TITLE
Unable to get the array list of getDirtyRows. I'm able to get the length but not array list.. I'm getting undefined if i try to access the array

### ISSUE THREAD

**Issue by ebineson** [angular-ui/ui-grid#5637]
Please make sure each of the following is true before submitting a new issue.  We are a small team with limited time and it is very difficult to manage issues if they aren't reported correctly.
- [ ] This is a bug report, not a question on how to use the grid.  
  Use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions.
- [ ] You have searched the open issues to see if this bug has been filed before.  We don't want duplicate issues.
- [ ] You have reviewed the tutorials and documentation to ensure you are using the grid correctly. [ui-grid.info](http://ui-grid.info/docs/#/tutorial)
- [ ] You are using the latest version of the grid. Older versions are not patched or supported.
- [ ] You have provided steps to recreate your bug.  A plunkr is even better.

**Comment by ebineson** [comment]
http://plnkr.co/edit/fgLpa2yDRqTiXaHd6s9t?p=preview

Here's the plunker

**Comment by mportuga** [comment]
That is because you have to do row.**entity** to get the value in the array. The reason for that is because getDirtyRows returns a grid row object rather than a element from the data array. I was able to figure that out by doing a console.log on the $scope.dirty that you created.
http://plnkr.co/edit/ltkeHcwUVhbe8vF55Mma?p=preview
