### ISSUE TITLE
Using URL string for headerCellTemplate does not work

### ISSUE THREAD

**Issue by jgunderson-IAS** [angular-ui/ui-grid#5717]
I have an issue with header cell templates not displaying if I try and use a URL string that should fetch the template. The network tab shows it has been loaded yet the header cell will not show content. If I use inline html it works fine. Here is a plunkr to show what is happening: 

http://plnkr.co/edit/b0MNuXPgn485N1HyHjQC?p=preview

The first column in columnDefs has a url and the second has inline html. Any help would be much appreciated.

**Comment by csvan** [comment]
Possible dup of https://github.com/angular-ui/ui-grid/issues/4514

You can work around this issue (at least I did) by injecting the html in question into your template cache.

**Comment by david-hanger** [comment]
Since I recently had a similar problem trying to use a URL value for **filterHeaderTemplate** (and getting empty content), I posted a [comment with a recommended fix](https://github.com/angular-ui/ui-grid/pull/5311#issuecomment-324158897) to the pull request #5311.  I thought I'd reference that comment here, in case anyone else comes across this before a better fix is applied.

The above recommended workaround is basically to prefetch the template into **$templateCache** before defining the **gridOptions**.  My recommendation in the pull request fixes template URL values to work as expected (as they do for **cellTemplate** and some others) without requiring such a prefetch.
