### ISSUE TITLE
Rows not aligning with check-marks on side

### ISSUE THREAD

**Issue by samunt** [angular-ui/ui-grid#5812]
The odd time, as I load data, the rows do not align with the check-marks on the left side.  Happens when scrolling through last few rows. Have changed row height back to default, did not help
![Uploading alignment.gif…]()

<img width="827" alt="screen shot 2016-11-14 at 1 17 01 pm" src="https://cloud.githubusercontent.com/assets/19476404/20277191/8f8da358-aa6d-11e6-9bca-f46ded98ddf9.png">

**Comment by lmame** [comment]
It is still happening in the latest release and even in the example:
http://ui-grid.info/docs/#/tutorial/210_selection

![bug ui grid](https://user-images.githubusercontent.com/361351/29253125-6f08fe00-802a-11e7-9ddf-d5bd1ff48bbf.png)

**Comment by lmame** [comment]
The issue appears when:
-> You scroll down at the very end,
-> Your mouse is hovering the last checkbox on the bottom,
-> You use the wheel mouse button to try to scroll down,

The data part does not move, the checkbox part scrolls a little, hence the misalignment.

**Comment by lmame** [comment]
It seems the problem comes from the height of left column. It does not take the full height but "cuts" it to leave the place for the horizontal scrollbar I suppose.
`<div role="rowgroup" class="ui-grid-viewport ng-isolate-scope" ng-style="colContainer.getViewportStyle()" ui-grid-viewport="" style="overflow: hidden;">`
In the ui-grid example the height is 321px, the rest is the placeholder.
![2017-08-13_14-02-32](https://user-images.githubusercontent.com/361351/29253386-1ef5ad0e-8030-11e7-8d49-9f69ed7feaae.png)

If I manually change the height to cover the place holder (so overall 328px) then there is not desync.
![2017-08-13_14-04-09](https://user-images.githubusercontent.com/361351/29253388-4ce5e148-8030-11e7-9a57-966024476cd4.png)

So I guess the calculation for the scroll should take into account the placeholder height (the 17px) so it does not continue to scroll in this case.

**Comment by lmame** [comment]
One (bad) solution in the meantime is to disable horizontal scrolling:
enableHorizontalScrollbar: 0

**Comment by artemmikhailov** [comment]
Another (bad) solution if horizontal scrollbar is required, set `overflow: scroll` for `.ui-grid-render-container-body .ui-grid-viewport`. The column resizing will work with viewport scrolling but the horizontal scroll-bar will be displayed constantly even if it’s not needed.

**Comment by artemmikhailov** [comment]
`div.ui-grid-scrollbar-placeholder` is shown due to [GridRenderContainer.js#L746](https://github.com/angular-ui/ui-grid/blob/21819c57474bf4451f3126985cfccf294c4c01e2/src/js/core/factories/GridRenderContainer.js#L746) and is not hidden for left-side container in [GridRenderContainer.js#L776](https://github.com/angular-ui/ui-grid/blob/21819c57474bf4451f3126985cfccf294c4c01e2/src/js/core/factories/GridRenderContainer.js#L776) unlike the same placeholder for body container is [(GridRenderContainer.js#L763)](https://github.com/angular-ui/ui-grid/blob/21819c57474bf4451f3126985cfccf294c4c01e2/src/js/core/factories/GridRenderContainer.js#L763).
Even if `div.ui-grid-scrollbar-placeholder` was hidden correctly during grid loading, I can not find (in GridRenderContainer.js) any relevant changes observers in order to activate `scrollbar-placeholder` in time - when horizontal scrollbar of  body-viewport becomes enabled after data-columns resizing.

**Comment by javierpacareu** [comment]
Guys did anyone find a solution to this issue??

**Comment by lmame** [comment]
Not from me... I did not have the time to look at it sadly :(

**Comment by DeepakJassi** [comment]
In my case, the rows were not aligned due to the top-left corner panel of the ui-grid. So I added height for the panel and it solve my problem of checkbox alignment.

.ui-grid-header .ui-grid-header-viewport {
  height: 28px !important;
}

Or you can try,
 .ui-grid-header-viewport {
  height: 28px !important;
}
