### ISSUE TITLE
Ui-grid horizontal scroll is not present when data is not available.

### ISSUE THREAD

**Issue by Shabbir-Saifee** [angular-ui/ui-grid#5838]
Please make sure each of the following is true before submitting a new issue.  We are a small team with limited time and it is very difficult to manage issues if they aren't reported correctly.

- [x] This is a bug report, not a question on how to use the grid.  
Use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions.
- [x] You have searched the open issues to see if this bug has been filed before.  We don't want duplicate issues.
- [ ] You have reviewed the tutorials and documentation to ensure you are using the grid correctly. [ui-grid.info](http://ui-grid.info/docs/#/tutorial)
- [ ] You are using the latest version of the grid. Older versions are not patched or supported.
- [ ] You have provided steps to recreate your bug.  A plunkr is even better.

**Comment by mportuga** [comment]
Closing for lack of clarity. Please make sure to describe the bug and include either a screenshot or a plunkr demonstrating the issue.

**Comment by kj-johnson** [comment]
I had this issue on Chrome only back in September (IE and Firefox did not exhibit the behavior). I was able to fix it by removing my custom CSS for the grid and putting it back in piece by piece until it broke again. The problem was having a margin on the top of the ui-grid canvas (between the header cells and the body cells of the ui-grid).

In particular, the offending css was the .ui-grid-canvas margin-top.

Here's a plunker showing the issue (note that you can fiddle with the css and grid options, this was how we had it set up, but even using the built-in scrollbars they are greyed out and disabled on an empty grid.
[Plunker](http://plnkr.co/edit/TE3fNmNdhLwTj6Pb7BhS?p=preview)
