### ISSUE TITLE
Parse error on cellnav when value content a space

### ISSUE THREAD

**Issue by W-prog** [angular-ui/ui-grid#5965]
Hello, 

When cell-nav activate, if I navigate on cell grid width space, you can see this error

Error: [$parse:syntax] http://errors.angularjs.org/1.5.7/$parse/syntax?p0=PRENOM&p1=is%20an%20unexpected%20token&p2=12&p3=BO06613643%20PRENOM%20INCONNU&p4=PRENOM%20INCONNU
    at angular.js:38
    at throwError (angular.js:14343)
    at t.ast (angular.js:14096)
    at ud.compile (angular.js:14559)
    at kc.parse (angular.js:15488)
    at g (angular.js:15653)
    at p.getCellDisplayValue (ui-grid.min.js:7)
    at ui-grid.min.js:11
    at m.$broadcast (angular.js:17767)
    at Object.h.cellNav.broadcastCellNav.j.cellNav.broadcastCellNav (ui-grid.min.js:11)

I precised error with ui-grid.js on : 
at Grid.getCellDisplayValue (ui-grid.js:5564)
values.push(grid.getCellDisplayValue(currentSelection[i].row, currentSelection[i].col));

And :

 at Object.uiGridCtrl.cellNav.broadcastCellNav.grid.cellNav.broadcastCellNav (ui-grid.js:15367)
_scope.$broadcast(uiGridCellNavConstants.CELL_NAV_EVENT, newRowCol, modifierDown, originEvt);

values.push(grid.getCellDisplayValue(currentSelection[i].row, currentSelection[i].col));

This function "getCellDisplayValue" don't manage the space char ?

**Comment by maxmarkus** [comment]
I am using also latest version (4.0.2) and see the same error. As soon as I have ui-grid-cellNav activated in the table, this errors shows up when clicking into a cell with content that has spaces.

    at ..
    ....
    at h.getCellDisplayValue (libs.min.js:18)
    at libs.min.js:22
    at m.$broadcast
    at Object.s.cellNav.broadcastCellNav.u.cellNav.broadcastCellNav

**Comment by W-prog** [comment]
Yes for me it's a bug non ? How can fixed it ?

**Comment by fridjon** [comment]
This seems to be caused by the accessibility features are attempting to read the value in the grid cell being navigated to. This triggers parsing of the contents of the grid cells which fails if the content of cell is not parseable. (see addAriaLiveRegion() function in ui-grid/src/features/cellnav/js/cellnav.js : line 775).

In any case, I think the accessibility feature should only run if it is being used. As far as I can see, the module ngAria must be included in the project in order for the screen reader to read this aloud. Perhaps it would be better to only activate this accessibility functionality only if the angular module ngAria is active.

**Comment by W-prog** [comment]
@fridjon : thanks for the fix and sorry for the late response . I don't have cellnav.js in my ui-grid, just a ui-grid.js file
This file ui-grid.js contain the module cellNav like this 
`var module = angular.module('ui.grid.cellNav', ['ui.grid']);`
and too addAriaLiveRegion() at the line 15469

The version of my file is v3.2.9 and I have add your fix and it's works very well.
The best is your fix that include in the futur version

In m reflexion, i've trying include angular-aria in my app but width no succes. I have always the same problem.
