### ISSUE TITLE
Slow rendering (2 minutes)

### ISSUE THREAD

**Issue by pvila89** [angular-ui/ui-grid#6057]
Hi,

I'm trying to render a grid that has 4.562 registers with 16 columns. The problem is that the rendering operation takes more than 2 minutes. (it happens in all browsers)

Here I attach an example of the resulting grid.

![image](https://cloud.githubusercontent.com/assets/3186791/23613983/bf0bd548-0281-11e7-8dcf-2d7d2d07c0c8.png)

I've been testing my application and it's not a server problem, the cause is when the grid is trying to render the data.

The grid allows you to modify cells, filter, sort the elements and  the version used is the last.

Here is some of the grid configuration:

![image](https://cloud.githubusercontent.com/assets/3186791/23614831/9e389d80-0284-11e7-9d62-f610af252090.png)

![image](https://cloud.githubusercontent.com/assets/3186791/23614052/f703c370-0281-11e7-9903-675f69d55a97.png)

![image](https://cloud.githubusercontent.com/assets/3186791/23614073/080e7b9c-0282-11e7-993b-5759d2f72243.png)

Removing some columns I've improved  the render time, but it's still slow, 1:30 minutes.

I don't know if I'm missing a configuration.

Could you help me?

Thank you all in advance.

**Comment by mportuga** [comment]
I have never seen such a slow rendering time before and we use UI-Grid at my company with almost all features turned on. The only difference that I see on yours is the @Html.raw thing. I've never seen that being used before, and I don't know what kind of impact that would have on performance. I am also wondering how many rows of data you are trying to load at once.

I tried recreating a grid like yours via plunker and was not able to reproduce that issue:
http://plnkr.co/edit/Wwsl0bsL7IqoUALKAg0D?p=preview

You can feel free to mess with it if you think the issue is on our side. Otherwise, I could suggest [ag-grid](https://www.ag-grid.com/) as a good alternative for performance.
