### ISSUE TITLE
OnRowsRendered fired when opening modal

### ISSUE THREAD

**Issue by aitorMolinuevo** [angular-ui/ui-grid#6097]
Hi,

I have developed a custom directive which opens a modal with a selectable table for filtering. When I open the modal, without doing anything else, the event onRowsRendered is fired but the grid data is the same. Anyone knows how to avoid to this event get fired? 

Thanks in advance.

**Comment by rescru** [comment]
If the grid scrolls to view your modal this may trigger the event,  something worth checking perhaps?

**Comment by aitorMolinuevo** [comment]
@rescru is there a way to avoid the event firing?

**Comment by rescru** [comment]
@aitorMolinuevo not sure I would want to prevent it otherwise there may be rows that should show that aren't getting shown.

I have only been using this control a short while. There may be a way however I am not sure. I won't be able to take a look at the code for a good couple hours, hopefully someone else can advise
