### ISSUE TITLE
ui-grid v4.x not on NPM

### ISSUE THREAD

**Issue by aplocher** [angular-ui/ui-grid#6139]
According to issue #5819 ui-grid v4 wasn't up on NPM (back in December).  That has since been closed, but when I check NPM I'm seeing v3.2.11 as the latest.

https://www.npmjs.com/package/angular-ui-grid

Am I missing something?

**Comment by aplocher** [comment]
Ugh immediately after posting this question I tried `npm install angular-ui-grid@4.0.3 --save` and it worked fine.

Not sure if this should remain open - shouldn't the most recent version show as 4.0.3?  How would someone get a list of available versions - I just guessed and it worked.

**Comment by mattbrunetti** [comment]
@aplocher Right now [version 3.2.11](https://github.com/angular-ui/ui-grid/tree/v3.2.11) is the most recently released version, even though [version 4.0.3](https://github.com/angular-ui/ui-grid/tree/v4.0.3) is the highest version. Version 3 continues to have minor and patch releases even though version 4 is out. That's why it says "3.2.11 is the latest of 22 releases" on NPM. 

In regard to the most recent version being installed by default, as opposed to the highest version:

Agree this isn't the ideal behavior, but it's an issue with this feature of NPM...

> By default, npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag.

Source: https://docs.npmjs.com/cli/dist-tag

Maybe move your issue to [the NPM repo](https://github.com/npm/npm)?

**Comment by mportuga** [comment]
Thank you for looking into this Matt. I plan on working on releasing 4.0.4 soon, so hopefully that will help with this.
