### ISSUE TITLE
space to right of rows when no width is given

### ISSUE THREAD

**Issue by Blindsyde** [angular-ui/ui-grid#6371]
I have a site where we show many uiGrid's. Previous to the latest update we always had scrollbars showing whether or not there was anything to scroll which worked well, we also never set widths on any columns, we just let uiGrid keep each column at what seemed to be an automatic width.

Today I have upgraded to 4.0.6 and now the scroll bars are missing, and adding `enableHortizontalScrollbar: uiGridConstants.scrollbars.ALWAYS` or `enableVerticalScrollbar: uiGridConstants.scrollbars.ALWAYS`  doesn't seem to make a difference nor does it add the scroll bars back in, also the more important part is every one of the grids now has white space to the right of all the rows (where the scrollbar would normally be)

![image](https://user-images.githubusercontent.com/8527885/29589520-c66209a6-8752-11e7-849e-b34bb2de8373.png)

My fiddle below will both illustrate the white space to right of rows and that the scrollbars setting doesn't actually give scrollbars:
https://jsfiddle.net/Blindsyde/rtj8vxwk/

**Comment by RobPierce** [comment]
I've found the reason for the space to the right of columns, it's to do with the fix for #5981 because column widths are now rounded to integers and any remaining space is only distributed between asterisk column widths, not percentage column widths so if you have some or all percentage column widths and no asterisk column widths, you will have some width left over. I'm about to submit a PR to remedy this.

**Comment by Blindsyde** [comment]
Great thank you!

**Comment by mportuga** [comment]
https://github.com/angular-ui/ui-grid/pull/6513
