### ISSUE TITLE
Selected groupings selects all of that column value no matter if filter is applied

### ISSUE THREAD

**Issue by piller187** [angular-ui/ui-grid#6418]
I have a grid and one of the columns is a status field. It can have values like Open, Accepted, Rejected, etc. If I filter the grid on status and I group my grid by another column and click the header to select all the grouped line items ALL items (even if NOT filtered) get selected. I would think the desired functionality is that ONLY the filtered items get selected.

When you call vm.gridApi.selection.getSelectedRows(); is when you notice that all items, even those not filtered, are included/selected.

**Comment by mportuga** [comment]
I believe this is related to #6479

**Comment by AndreaBittner** [comment]
Hi @mportuga,
I decline, that this is related to the mentioned issue. I have the same problem and would suggest a fix.  
The problem, please do it with this [data samples in plnkr](http://plnkr.co/edit/hPdIKG0R5vJTxY2uGY23?p=preview )
1. 'State' is grouped and sorted. Add filter 'Caroline' for Column 'Name'
![image](https://user-images.githubusercontent.com/784753/43590028-4f965a88-9670-11e8-986a-7ef9361dd86a.png)
2. Select groupHeader "Alabama" (I marked it)
3. Remove the filter of column 'Name'
4. open 'State' Alabama, Alaska, .. 
you can see, that Caroline from Alabama is selected, but also more entries afterwards.
![image](https://user-images.githubusercontent.com/784753/43590205-bdbf21ca-9670-11e8-91b2-8a96ee866aa3.png)

What I found out:
 'toggleRowSelection()' will be called for each row, which is a child of the treeNode. But when filtering, the tree isn't correct and row.treeNode contains children from the treeNode afterswards, which is invisible because of the filtering.
![image](https://user-images.githubusercontent.com/784753/43590863-4f353256-9672-11e8-9a00-68551ecea570.png)

I made a quickfix and add `row.visible === false` for preventing the toggling, which solves the problem and that case and didn't select filtered out rows, which are invisible. 
But the treeNode is still wrong. 
What do you think?

```javascript
/**
         * @ngdoc function
         * @name toggleRowSelection
         * @methodOf  ui.grid.selection.service:uiGridSelectionService
         * @description Toggles row as selected or unselected
         * @param {Grid} grid grid object
         * @param {GridRow} row row to select or deselect
         * @param {Event} evt object if resulting from event
         * @param {bool} multiSelect if false, only one row at time can be selected
         * @param {bool} noUnselect if true then rows cannot be unselected
         */
        toggleRowSelection: function (grid, row, evt, multiSelect, noUnselect) {
          if ( row.enableSelection === false || row.visible === false ) {
            // added condition for invisible rows, f.e. filtered out before
            return;
          }
```

Doing it the other way aroung with first selecting a bunch of rows and then filtering; an exporter woudn't  note the filtering, because getSelectedRows() (Z~27240) gives only selected rows. Because of that, I added `&& row.visible` here:
```javascript
getSelectedRows: function (grid) {
           return grid.rows.filter(function (row) {	         
  return grid.rows.filter(function (row) {
return row.isSelected && row.visible;
           });	        
   });
```

**Comment by WieldSoftwareDevelopement** [comment]
This is still an issue in 4.11.0.

I've patched my toggleRowSelection function as well, which resolves this subtle yet troublesome bug for me.

line: 27475
`
//only select row in this case
if (!(selected && noUnselect) **&& row.visible**){
`
