### ISSUE TITLE
cellfilter to dd-MM-yyyy doesn't filter

### ISSUE THREAD

**Issue by gerut** [angular-ui/ui-grid#6466]
I tried to change cellfilter to dd-MM-yyyy but it doesn't work for filtering. The filter only works with yyyy-MM-dd format. Is there an possibility to change that to dd-MM-yyyy? Besides I need the date format for the asc desc function. Converting to  a string might be a solution but not for asc desc date formates.
![image](https://user-images.githubusercontent.com/11926760/32783031-a67d1e66-c94a-11e7-994c-d4fd89651f06.png)
![image](https://user-images.githubusercontent.com/11926760/32783109-ee680362-c94a-11e7-8f2a-74d71c1cdd63.png)
![image](https://user-images.githubusercontent.com/11926760/32783160-0b057270-c94b-11e7-8995-cb263173df9b.png)

**Comment by rajeshilluri** [comment]
Please try to use uib date picker.. Comment

**Comment by freedomlang** [comment]
it's wired, the filter works on regular input outside ui-grid

**Comment by jniles** [comment]
@gerut, I know this is an old issue, but I'll post some ideas here in case you or someone else runs into this. 

First, `ui-grid` will filter the underlying _data_ by default when you use a plain inline filter.  To filter the rendered value, you need to use [filterCellFiltered](http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef#properties_filtercellfiltered), which will take the value after a filter has been applied to the cell.  So, instead of the underlying data, it will filter on what the view looks like.

Another thing that may help in the future is changing the column `type`.  We have found that sometimes `ui-grid` uses alphabetic sorting when we want to have numeric sorting on a number column, for example.  By setting `type : 'date'`, `type: 'number'`, etc, you can change the filter and sorting behavior.
