### ISSUE TITLE
ui-grid do not show well in firefox, such as grid menu and so on

### ISSUE THREAD

**Issue by screamsyk** [angular-ui/ui-grid#6533]
there are some problem in firefox that cause the ui-grid do not work well.
Are there some methods to resolve this? @mportuga 
![1](https://user-images.githubusercontent.com/25660357/34972752-9d1772cc-fabe-11e7-80cd-958906eda8fe.png)

**Comment by mportuga** [comment]
I believe this is a side effect of one of the changes that I did yesterday. I might just revert that change.

**Comment by yraveh** [comment]
ר
נשלח מסמארטפון ה-Samsung Galaxy שלי.
-------- הודעה מקורית --------ככךok  m.מאת: Marcelo Sauerbrunn Portugal לא  notifications@github.com> תאריך:   06:59  (GMT+02:00) אל: angula הגגr-ui/ui-grid <ui-l@noreply.github.com> עותק: Subscribed <subscribed@noreply.github.com> נושא: Re: [angular-ui/ui-grid] ui-grid do not show well in firefox, such as grid mהenu and so on (#6533) גגהClosed #6533 via #6540.

—
You are receiving this because you are subscribed to this thread.ll
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular-ui/ui-grid","title":"angular-ui/ui-grid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/angular-ui/ui-grid"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #6533 via #6540."}],"action":{"name":"View Issue","url":"https://github.com/angular-ui/ui-grid/issues/6533#event-1427557142"}}}
