### ISSUE TITLE
Select All chekbox getting checked even when there is no data in grid

### ISSUE THREAD

**Issue by DP-Prakash** [angular-ui/ui-grid#6582]
I am using the latest version of ui-grid. I have enabled the row selection header. The select all checkbox gets checked by default even when there is no data in the grid. It works properly in version 4.0.6
[http://plnkr.co/edit/VKHAP7i46QEWiTmovj2F?p=preview](http://plnkr.co/edit/VKHAP7i46QEWiTmovj2F?p=preview) - 4.1.0

**Comment by mportuga** [comment]
So, after looking at your plunker i realized that this issue is due to CSS alone. I was able to verify this by toggling the version of the CSS file between 4.0.6 and 4.1.0 and the issue is not present with the css  in 4.0.6, regardless of the js version.

The issue also appears to have been introduced on 4.0.7.
The following are identified as the probable causes:
https://github.com/angular-ui/ui-grid/commit/aae3f9d965b1e39a32d1471fcd025afeb3d006b6
https://github.com/angular-ui/ui-grid/commit/d1aee28b01782b42061e2599c5b285399ec144fa

**Comment by mportuga** [comment]
Here is a plunker from a duplicate issue with the latest version showing the same issue:
http://plnkr.co/edit/5F6tuNuft7QDhxgKCRPy?p=preview
"When no data provided to grid, all selection checkbox remains checked."

**Comment by BMK91** [comment]
So, it should be updated in next release, right ... ?

**Comment by mportuga** [comment]
I am kind of stretched thin right now, but we are definitely willing to accept PRs for this. I will work on it soon if I get a chance, but if anyone else can work on it, that will be good too.

**Comment by mportuga** [comment]
I made a mistake, this is not a CSS issue.
