### ISSUE TITLE
How to invoke inline-edit functionality using javascript/jquery?

### ISSUE THREAD

**Issue by sohampshetty** [angular-ui/ui-grid#6645]
Inline-edit functionality will be active when a user uses ui and double click on a grid cell. For some reason, I want to do that using javascript something like `$('ele').trigger('dblclick');` 

Is it possible? If yes, how do I find `id` of the cell on `mouseenter` and trigger the double-click on that id so that it shows edit template.

**Comment by mportuga** [comment]
I don't recommend that you do this because I don't believe having a trigger like that on mouse enter is  ever going to be performant, but you can try the following: 
http://plnkr.co/edit/mZcZATwzizqhax6E9ZKr?p=preview

I added a cellClass to the name column and ensured that attached an event to those cells that does what you are asking when mouse enter is triggered on those columns. See lines 33 and 100 - 107.

In the future, please use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-ui-grid) or [Gitter](https://gitter.im/angular-ui/ui-grid) for questions.
