### ISSUE TITLE
need help to integrate with angular 6

### ISSUE THREAD

**Issue by vijaynet10** [angular-ui/ui-grid#6810]
how to use ui-grid in angular 6

**Comment by mportuga** [comment]
It is not supported at the moment. I have a plan for supporting it, but it is slow going due to the small size of the team and the need to stabilize it first. Best suggestion that I have for you is to find a wrapper.

**Comment by vijaynet10** [comment]
may i join with your team , if yes then send the requirements

**Comment by mportuga** [comment]
It is possible for you to join, but you have to show me a bit of what you can do and your commitment first. If you could help me do the following:

* Fix bugs (help wanted or good first issue)
* Write unite tests (check coveralls and improve the code coverage of files which have little to no coverage)
* Help with protractor (as part of the plan for upgrading to angular 6, I want to get the existing protractor tests to pass consistently and run on Travis)

All of those activities will aid me in stabilizing ui-grid and getting it ready for angular6 support, so if you can open pull requests to help with them, then I could give you maintainer status. As a side note, please use commitzen when making commits for ui-grid, since we use that as a way to automatically generate a change log. I also recommend reading the contributor.md file.

**Comment by vijaynet10** [comment]
**ok i will join with your Team**
