### ISSUE TITLE
Aria Roles

### ISSUE THREAD

**Issue by apobbati** [angular-ui/ui-grid#696]
Is it possible to add aria roles to ng-grid?

grid
columnheader
row
gridcell

This would help greatly with accessibility.
Thanks,

**Comment by hohwille** [comment]
Can someone please explain.
http://ui-grid.info/ is pointing to this repository. So does wontfix mean that ui-grid will never be accessible?
Or what does no-more-2x-issues mean? This issue is not fixed in 3.x there is no single role or aria-* attribute in the generated HTML. The ui-grid is very cool but in the context of accessibility and screen-reader support the worst option on this planet so far. Is there anything planned? Support welcome?

**Comment by hohwille** [comment]
If you want to get an quick impression how a blind person "sees" your content, quickly download and install NVDA:
http://www.nvaccess.org/

Then in case you do not actually need assistive technology set volume to zero and open the NVDA speech viewer to see what NVDA would read to a blind person. Then probably even unplug your mouse and try to read and edit your website with just the keyboard and the information your get in the speech viewer. This might open your mind to how a blind person "sees" the web and how you could help with WAI-ARIA:
http://www.w3.org/WAI/intro/aria.php

The general idea is that you use role attributes to classify main elements so assistive technology like screenreaders can understand that this DIV is actually a listgrid. Then additional aria-* attributes can reveal even more details. Thanks for taking care :)

**Comment by PaulL1** [comment]
It's open for ui-grid: #2840
