### ISSUE TITLE
filter not showing for restored columns

### ISSUE THREAD

**Issue by carbuz2** [angular-ui/ui-grid#6969]
Hi,

I created a grid with a menu and filters for each columns.

<img width="506" alt="Screen Shot 2019-05-07 at 18 04 36" src="https://user-images.githubusercontent.com/18289263/57314862-c621a100-70f2-11e9-8fb5-48e5992fcf01.png">

 When I delete a row (in the example the row "Description") and I recreate it in the menu, the related filter disappears: 
<img width="563" alt="Screen Shot 2019-05-07 at 17 58 59" src="https://user-images.githubusercontent.com/18289263/57314503-0af90800-70f2-11e9-9cbf-add7584a393e.png">

Is there a way to reload with the column also the filter? 

I tried a very poor fix like:

```
gridApi.core.on.columnVisibilityChanged($scope, function (column) {
     gridOptions.enableFiltering = true;
     gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);                 
 })
```

but it does not work.

Thanks

**Comment by NightlyFox** [comment]
i was able to fix this within the minified and non-minified versions.

do a search and replace in the ui-grid.min.js file
SEARCH FOR: delete r.col.updateFilters
REPLACE WITH: delete r.col.filterable,delete r.col.updateFilters


in the non minified version the place to update is under uiGridFilter directive.
there is 
 $scope.$on( '$destroy', function() {
              delete $scope.col.updateFilters;
 });

scope on destroy defined but it needs to be 
$scope.$on( '$destroy', function() {
              delete $scope.col.filterable;
              delete $scope.col.updateFilters;
 });

The problem is that in the latest release they are checking for col.filterable but do not reset the value whenever the column is destroyed. 
There is a check in updateHeaderOptions that only executes the setFilter function if the old filterable value and new filterable value are different. Because the old filterable value is now cached with the column cache it is never destroyed and retains the same filterable value. 

in this case i am using the fact that $scope.col.filterable value exists to know that the filters have been created, if it is undefined, then it needs to be created and added to the DOM. because it is removed from the DOM whenever it is destroyed, it $scope.col.filterable needs to be reset!

hopefully i explained that well lol. Not sure if this is how they intended it to work, but i do know that the replacing the above code fixes the bug!

**Comment by WieldSoftwareDevelopement** [comment]
Thanks for the fix!

**Comment by DavidMorton** [comment]
Honestly, I'd love to see someone dive in there and just fix this. I'll be honest, I tried to submit the fix, but given the scope of the fix (and the one-liner nature of the fix), I don't have the bandwidth for a proper commit message/description/etc. :/ . Anyways, a pull request is out there for the EXACT thing the OP suggested, and I tested it on a grid I'm building right now and it works just fine.
