### ISSUE TITLE
uiGridExpandableRow - scrolling the expanded rows hides the subgrid

### ISSUE THREAD

**Issue by vipulDessai** [angular-ui/ui-grid#7061]
When grid rows are more than 20, scrolling the grid hides the visible sub grid.

Observed that on scroll the $scope.row.expandedRendered is set false for directive uiGridExpandableRow, but the $scope.row is in visible range and i believe it should not be set false at this point.

**Comment by badgamerbad** [comment]
Need help, i analyzed the functions which are triggered on scroll, found that the directive uiGridExpandableRow gets destroyed when the new renderedRows is set and when this directive is destroyed i.e the expanded row has a property expandedRendered which is now set false and remains false while scrolling vertically.

**Comment by badgamerbad** [comment]
When _**expand all**_ rows is triggered and while scrolling vertically, in the function _**this.rowStyle**_ the _**translateY**_ variable is not set properly as the _**rowContainer.grid.options.rowHeight**_ is taken instead of individually expanded rows height.

Therefore creating a new variable for setting this _**translateY**_ and using the function _**updateViewableRowRange**_ to calculate this value from row index 0 to _**currentTopRow**_ in a _**for**_ loop.
