### ISSUE TITLE
We need to upgrade Angular to 1.8.0

### ISSUE THREAD

**Issue by caok2709** [angular-ui/ui-grid#7091]
Noticed that our angular version is still 1.7.9
Latest angular 1.8.0 published recently.

**Comment by carlas0fia** [comment]
I'm upgrading too to 1.8.0, could it be a problem?

**Comment by natpicone** [comment]
Look like 2.8.3 supports angularjs 1.8.0 but build has failed.
@mportuga can you please check this out?
Thx

**Comment by natpicone** [comment]
After more checks here is the status:
- version 4.8.3 supports angularjs 1.7.9
- master has support for angularjs 1.8.0 but build is broken (maybe it just needs to be re-tried) and it has not been tagged as new release

I really need that somebody take a look at this otherwise I won't be able to close the security issue of angularjs 1.7.9.

Github security panel doesn't report any issue because the master dependencies are correct. It doesn't know that the master version has not been released yet.

@caok2709 / @mportuga can you help on this please?

Thanks

**Comment by cristianp6** [comment]
Hi all!
I need to upgrade to angularjs 1.8.0 too, can the broken build be fixed and release it?
Many thanks!

@mportuga

**Comment by cristianpascottini** [comment]
Hi guys, **v4.8.5** published on npm registry [still depends on AngularJS 1.7.9](https://github.com/angular-ui/ui-grid/pull/7117#issuecomment-698989413).

**Comment by mportuga** [comment]
Whoops, I missed one package.json file, thanks for the catch

**Comment by Den-dp** [comment]
Литч

пт, 25 сент. 2020 г., 22:19 Marcelo Sauerbrunn Portugal <
notifications@github.com>:

**Comment by cristianpascottini** [comment]
Great, now it installs AngularJS v.1.8.0! Thanks! 👍🏻
