### ISSUE TITLE
Missing columns when using horizontal scrolling with RTL direction grid

### ISSUE THREAD

**Issue by gilbehar** [angular-ui/ui-grid#7126]
When using ui-grid with latest Chrome (85+) or Edge, and setting up RTL grid, the left columns disappear while scrolling to left.

You can reproduce this issue easily on the RTL Support tutorial page:
[](http://ui-grid.info/docs/#!/tutorial/Tutorial:%20120%20RTL%20Support)

There suppose to be 15 columns, when loading the grid you can see the first 3  which is ok, 
but when scrolling left after the 5th column you do not see column 6,7 etc...  and columns 4 & 5 suddenly disappear

**Comment by tomyam1** [comment]
This seems to be because the [RTL scroll type detection](https://github.com/angular-ui/ui-grid/blob/v4.9.0/packages/core/src/js/services/ui-grid-util.js#L1007) in ui-grid needs to be updated

The recent code from https://github.com/othree/jquery.rtl-scroll-type returns different results

We solves it temporarily by loading jquery.rtl-scroll-type and doing :

```typescript
ngModule.config(($provide: IProvideService) => {
    $provide.decorator('gridUtil', ($delegate: any) => {
        $delegate.rtlScrollType = () => {
            return $.support.rtlScrollType();
        }
        return $delegate;
    });
});
```

Can you verify if this works for you as well?

**Comment by gilbehar** [comment]
Thanks for your quick reply,

It works, but with a minor change $.support.rtlScrollType() is not a function so it should be

`return $.support.rtlScrollType;`

Many thanks

**Comment by mportuga** [comment]
Closed by https://github.com/angular-ui/ui-grid/pull/7130
