### ISSUE TITLE
Need to show concatenated fields in a ng-grid column. Not working.

### ISSUE THREAD

**Issue by getjewelfast115** [angular-ui/ui-grid#723]
Hi, 
I am new to Angular JS, I am trying to display items in a ng-grid. In a particular column, I have to concatenate two different model fields with a "-" sign. Can somebody please help me to have a solution for this?

I tried like this,
field : 'rollnumber' + '-' + 'name';
displayName : 'NameRollNumber'

But it is not working :( .

Thanks & Regards,
Jewel Jose

**Comment by robsilvia** [comment]
Here's a more elegant method:

Use a cellTemplate in your columnDefintions like such:

```
{name: "newField", cellTemplate: '<span ng-bind-template="{{row.entity.field01}} {{row.entity.field02}}"></span>'}
```

**Comment by jklaus** [comment]
Is there any way to call a scope level function rather than an object level function?  
I don't particularly want to add the function to the object if I can help it.
I've tried just defining a function within the field statement but that doesn't seem to work.

**Comment by robsilvia** [comment]
The way I ended of doing scope level field manipulation was using cell templates. Quick google search brings up, http://brianhann.com/6-ways-to-take-control-of-how-your-ui-grid-data-is-displayed/ which has a decent enough explanation of this works.

**Comment by jklaus** [comment]
Yeah I came across that.. I was looking for something more similar to the way you set mData in the (now legacy) DataTables.

For my specific use case I opted to go with a filter.  

Initially I thought at some point I'd need to do something similar to executing a function with mData but after a bit more thought I don't see any real instance where implementing a filter or ,as you mentioned, cell template wouldn't get the job done.

I'm in the midst of upgrading an older app to newer versions of things and was weighing DataTables vs ng-Grid (ui-Grid).  Obviously ui-Grid has come a long way.

**Comment by UnnamedSong** [comment]
@c0bra 
Thank you very much.
It works!

**Comment by cesee** [comment]
I think that the easiest way is to use a cell template surrounded by a span
<b>
{name: "NameRollNumber", cellTemplate: "<span>{{rollnumber}} -  {{name}}</span>"}
</b>

I think that this does not break the way angular works. Declaring a function just adds unnecessary extra work and dependencies.
I had to surround it with a span so that angular understands that it's an html template and not an html file

**Comment by UnnamedSong** [comment]
@cesee 
Right. I think It's a better way you want to display a simple template.
BTW, *cellTemplate: "<span>{{ rollnumber }}</span>"* will not work..
*{{ row.entity.fieldname }}* will work. :)

**Comment by cesee** [comment]
@UnnamedSong 
Thanks for the correction, I updated the answer.

**Comment by UnnamedSong** [comment]
You're welcome. My pleasure. xD

**Comment by Sampath-Lokuge** [comment]
Thanks a lot @cesee It works :)

If someone needs to align it within the cell, use as shown below.Cheers !

    cellTemplate: '<div class="ui-grid-cell-contents">{{row.entity.rollnumber}} - {{row.entity.name}}</div>',

**Comment by PaulL1** [comment]
You could also do this by using a function for your field in the column def - this is covered in the binding tutorial.

Sent from my iPhone

On 17 Dec 2015, at 2:59 AM, Sampath Lokuge <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot @cesee<https://github.com/cesee> It works :)

If someone needs to align it within the cell, use as shown below.Cheers !

cellTemplate: '<div class="ui-grid-cell-contents">{{row.entity.rollnumber}} - {{row.entity.name}}</div>',


-

**Comment by Cdvalencia** [comment]
Hi!

You must to add on your $scope.gridOptions.columnDefs, the next sentence: 

{name: "NameRollNumber", cellTemplate: "<span>{{row.entity.rollnumber}} - {{row.entity.name}}</span>"}

**Comment by vinaymeetu** [comment]
Thanks alot. Its works

**Comment by bhantol** [comment]
This breaks any filtering.

**Comment by PraveenGuda** [comment]
Grouping is not working for the columns in which we are using
 cell template

**Comment by veica** [comment]
I want to use aggregation on columns i dynamically calculate.
For instance I have delta of column A and column B, so if i want to have summing up of delta i can't use cell template. ( Summing as built-in: treeAggregationType: uiGridGroupingConstants.aggregation.SUM)

I used field:getDellta() and than function would return me delta of column A and column B, and i managed to get proper grouping, dynamically calculated when either A or B changes, but now I have function attached to each row, and it causing some other issues.

Is there alternative?
Thank you.

**Comment by goleafs** [comment]
when grouping, it does not seem to have any context for the row.entity 
COL_FIELD shows the wrong value (it's just used for sorting properly but we present a diff value)

basically instead of this:
`<div ng-if="!col.grouping || col.grouping.groupPriority === undefined || col.grouping.groupPriority === null || ( row.groupHeader && col.grouping.groupPriority === row.treeLevel )" class="ui-grid-cell-contents" title="TOOLTIP">{{ COL_FIELD CUSTOM_FILTERS }}</div>`

we need this

`<div ng-if="!col.grouping || col.grouping.groupPriority === undefined || col.grouping.groupPriority === null || ( row.groupHeader && col.grouping.groupPriority === row.treeLevel )" class="ui-grid-cell-contents" title="TOOLTIP">{{ row.entity.someField }}</div>`

but the second one does not work

**Comment by ebiale** [comment]
if i use a cell template, the sort work wrong, sort only the fieldA values, ignores the values of fieldB
 name: 'fieldA',
 displayName: fieldA,
 cellTemplate: '<a> <span>{{(COL_FIELD && (COL_FIELD!== row.entity.fieldB)) ? (grid.options.flag? "A: "+COL_FIELD : COL_FIELD) : "S/N: " + row.entity.fieldB </span> </a>'

**Comment by karandidwani** [comment]
Hi,

@c0bra I have similar type of requirement http://plnkr.co/edit/Tbbx5M?p=preview
it's just the string i am returning is a path (/user/folder/fileName.zip) and in my column I have made it a hyperlink so the user can click and download it. Now the problem is I dont wanna show them full path instead just the name of file (fileName.zip)

Now I can do substr(based on last occurence of "/") and return it and then it displays correct name in table, but the download path is also changed by just the name and file wont be downloaded.

Is there anyway I can alter the {{COL_FIELD}} and apply substr operations on it

I would really appreciate any help
