### ISSUE TITLE
Poor horizontal scrolling performance and $rootScope digests

### ISSUE THREAD

**Issue by rinckemd** [angular-ui/ui-grid#736]
I have a rather large page with lots of bindings, and a grid that horizontally scrolling with the first column pinned.

I noticed the re-draw was horrible, jumpy re-draw when scrolling horizontally.  Saw a lot of $root digests going on.  

Digging into the code, I see this $watch:
$scope.$watch('renderedColumns', function() {
            $timeout(self.setDraggables);
        });

That seems to fire continually as a scroll, and the $timeout is doing an apply.

If I change it to, the scrolling is smooth and great.
$scope.$watch('renderedColumns', function() {
            $timeout(self.setDraggables, 0, false);
        });

Do we need to digest on setDraggables?  I've love to cut down on the digests and get the scrolling working smooth.

**Comment by csvan** [comment]
I know this is old, but even as of 4.0 horizontal scrolling is still nearly unusable. I did some profiling, and it turns out that *every single scrollevent* triggers a full digest. This means that scrolling from left to right in a grid with about 200 columns and 5 rows causes in excess of *1000 digests*. I would love to help resolve this, but I am not sure where to start looking.
